trigger:
  - main
  - development

jobs:
  - job: macOS
    displayName: 'Build for macOS'
    pool:
      vmImage: 'macOS-latest'
    variables:
      configuration: Release
      scheme: 'TrominoPuzzle.Cli'
      sdk: macosx
    steps:
      - task: Xcode@5
        displayName: 'Build'
        inputs:
          actions: 'build'
          scheme: '$(scheme)'
          configuration: '$(configuration)'
          xcodeVersion: '12'
          destinationPlatformOption: 'macOS'
          packageApp: false
  - job: Windows
    displayName: 'Build for Windows'
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: VSBuild@1
        displayName: 'Build'
        inputs:
          solution: 'msbuild/TrominoPuzzle.sln'
          platform: 'x64'
          configuration: 'release'
          maximumCpuCount: true
          msbuildArchitecture: 'x64'
  - job: Linux
    displayName: 'Build for Linux'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: autoreconf --install --force --verbose --warnings=all
        displayName: 'autoreconf'

      - script: mkdir build && cd build && ../configure
        displayName: 'configure'

      - script: make
        displayName: 'make'
        workingDirectory: build

      - script: make check
        displayName: 'make check'
        workingDirectory: build

      - script: make dist
        displayName: 'make dist'
        workingDirectory: build

      - script: make distcheck
        displayName: 'make dist'
        workingDirectory: build
