async function createLitroMod(moduleArg={}){var moduleRtn;var d=moduleArg,f=import.meta.url,g="",h;try{g=(new URL(".",f)).href}catch{}h=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var k=console.error.bind(console),l=!1,m,n,p=!1;function q(a){a=`Aborted(${a})`;k(a);l=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");n?.(a);throw a;}var r;
async function t(a){try{var b=await h(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";}async function u(a,b){try{var c=await t(a);return await WebAssembly.instantiate(c,b)}catch(e){k(`failed to asynchronously prepare wasm: ${e}`),q(e)}}
async function v(a){var b=r;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){k(`wasm streaming compile failed: ${e}`),k("falling back to ArrayBuffer instantiation")}return u(b,a)}class w{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var x={},y=a=>{if(!l)try{a()}catch(b){if(!(b instanceof w||"unwind"==b))throw b;}finally{}},z=[],B=a=>{var b=z[a];b||(z[a]=b=A.get(a));return b},E,F=[],G=a=>{const b=a.length;return[b%128|128,b>>7,...a]},H={i:127,p:127,j:126,f:125,d:124,e:111},I=a=>G(Array.from(a,b=>H[b]));
d.addFunction=(a,b)=>{if(!E){E=new WeakMap;var c=A.length;if(E)for(var e=0;e<0+c;e++){var C=B(e);C&&E.set(C,e)}}if(c=E.get(a)||0)return c;c=F.length?F.pop():A.grow(1);try{A.set(c,a),z[c]=A.get(c)}catch(D){if(!(D instanceof TypeError))throw D;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...G([1,96,...I(b.slice(1)),...I("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;A.set(c,b);z[c]=A.get(c)}E.set(a,c);return c};
d.removeFunction=a=>{E.delete(B(a));A.set(a,null);z[a]=A.get(a);F.push(a)};var J,K,A,L={d:()=>q(""),c:()=>{},a:(a,b)=>{x[a]&&(clearTimeout(x[a].id),delete x[a]);if(!b)return 0;var c=setTimeout(()=>{delete x[a];y(()=>J(a,performance.now()))},b);x[a]={id:c,l:b};return 0},b:a=>{throw new w(a);}},M;
M=await (async function(){var a={a:L};r??=d.locateFile?g+"litro-wasm.wasm":(new URL("litro-wasm.wasm",import.meta.url)).href;a=M=(await v(a)).instance.exports;d._solve=a.g;J=a.h;K=a.e;A=a.i;a=K.buffer;new Int8Array(a);new Int16Array(a);new Uint8Array(a);new Uint16Array(a);new Int32Array(a);new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a);return M}());d.calledRun=!0;l||(p=!0,M.f(),m?.(d));
p?moduleRtn=d:moduleRtn=new Promise((a,b)=>{m=a;n=b});
;return moduleRtn}export default createLitroMod;
