async function createTrmnMod(moduleArg={}){var moduleRtn;var h=moduleArg,aa=import.meta.url,ba="",ca;try{ba=(new URL(".",aa)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var da=console.log.bind(console),k=console.error.bind(console),n=!1,ea,fa,ha=!1;function ia(a){a=`Aborted(${a})`;k(a);n=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");fa?.(a);throw a;}var ja;
async function ka(a){try{var b=await ca(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";}async function la(a,b){try{var c=await ka(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ia(d)}}
async function ma(a){var b=ja;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return la(b,a)}class na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var oa,p,pa,q,r,t,qa,v,w,ra=globalThis.TextDecoder&&new TextDecoder,x=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&ra)return ra.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
sa={},ta=a=>{if(!n)try{return a()}catch(b){if(!(b instanceof na||"unwind"==b))throw b;}finally{}};function ua(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var va=!1,wa=[];
function xa(){function a(){va=document.pointerLockElement===h.canvas}if(!ya){ya=!0;var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!va&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function za(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,ze:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Aa&&(e=Ba(a,f)))var l=y[e].Qd}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&Ca(e),wa.forEach(m=>m()),xa());return l}
var ya,z=12288,Da=!1,Ea=0,Fa=0,Ga=0,A={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ha={},Ia,B,Ja=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Ka=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},La=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ma=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Na=1,Oa=[],C=[],Pa=[],D=[],E=[],G=[],Qa=[],y=[],H=[],Ra={},Sa=4,Ta=0,Ua=a=>{for(var b=Na++,c=a.length;c<b;c++)a[c]=null;return b},Va=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=B[c](),g=f&&Ua(d);f?(f.name=g,d[g]=f):J||=1282;p[b+4*e>>2]=g}},Ba=(a,b)=>{a.ue||(a.ue=a.getContext,a.getContext=function(d,e){e=a.ue(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Wa(c,b):0},Wa=(a,b)=>{var c=
Ua(y),d={handle:c,attributes:b,version:b.ze,Qd:a};a.canvas&&(a.canvas.Td=d);y[c]=d;if("undefined"==typeof b.Le||b.Le)if((a=d)||(a=Xa),!a.Qe){a.Qe=!0;a=a.Qd;a.ef=a.getExtension("WEBGL_multi_draw");a.Ne=a.getExtension("EXT_polygon_offset_clamp");a.Me=a.getExtension("EXT_clip_control");a.Ue=a.getExtension("WEBGL_polygon_mode");Ja(a);Ka(a);La(a);a.Pd=a.getExtension("EXT_disjoint_timer_query");for(var e of Ma(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},Ca=a=>{Xa=y[a];
h.ctx=B=Xa?.Qd},Aa={},J,Xa,Ya=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},K=(a,b,c)=>{var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&
63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},N=a=>{var b=Ya(a)+1,c=M(b);c&&K(a,c,b);return c},kb=(a,b,c,d,e)=>{O=a;Za=d;var f=P;$a=!1;ab=function(){if(!n)if(0<bb.length){var g=bb.shift();g.af(g.Ve);if(cb){var l=cb,m=0==l%1?l-1:Math.floor(l);cb=g.Ye?m:(8*l+(m+.5))/9}f<P||setTimeout(ab,0)}else if(!(f<P))if(db=db+1|0,1==eb&&1<fb&&0!=db%fb)Q();else{0==eb&&(gb=performance.now());a:if(!n){for(g of hb)if(!1===g())break a;ta(a);for(l of ib)l()}f<P||Q()}};e||(0<b?jb(0,1E3/b):jb(1,1),Q());
if(c)throw"unwind";},$a=!1,Q=null,P=0,O=null,Za=0,eb=0,fb=0,db=0,bb=[],hb=[],ib=[];function lb(){Q=null;P++}function mb(){P++;var a=eb,b=fb,c=O;O=null;kb(c,0,!1,Za,!0);jb(a,b);Q()}var nb=0;function ob(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===nb)nb=b+1E3/60;else for(;b+2>=nb;)nb+=1E3/60;setTimeout(a,Math.max(nb-b,0))}}
var pb={},ab,cb,gb,qb,jb=(a,b)=>{eb=a;fb=b;if(O)if($a||=!0,0==a)Q=function(){setTimeout(ab,Math.max(0,gb+b-performance.now())|0)};else if(1==a)Q=function(){ob(ab)};else{if(!qb)if(globalThis.setImmediate)qb=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);qb=d=>{c.push(d);postMessage("setimmediate","*")}}Q=function(){qb(ab)}}},rb=[],sb=(a,b)=>{rb.length=0;for(var c;c=w[a++];){var d=105!=c;d&=112!=
c;b+=d&&b%8?4:0;rb.push(112==c?v[b>>2]:106==c?pa[b>>3]:105==c?p[b>>2]:t[b>>3]);b+=d?8:4}return rb};function tb(a){var b=R.Jd[a];b.target.removeEventListener(b.Fd,b.xe,b.Ld);R.Jd.splice(a,1)}function ub(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of R.Rd)if(e.ke==a&&d(e.ve,c))return;R.Rd.push({ke:a,Be:b,ve:c});R.Rd.sort((f,g)=>f.Be-g.Be)}function vb(a){R.Rd=R.Rd.filter(b=>b.ke!=a)}
function wb(){return navigator.userActivation?navigator.userActivation.isActive:R.ge&&R.Fe.Vd}function xb(){if(wb()){var a=R.Rd;R.Rd=[];for(var b of a)b.ke(...b.ve)}}function S(a){if(!a.target)return-4;if(a.Id)a.xe=function(c){++R.ge;R.Fe=a;xb();a.Od(c);xb();--R.ge},a.target.addEventListener(a.Fd,a.xe,a.Ld),R.Jd.push(a);else for(var b=0;b<R.Jd.length;++b)R.Jd[b].target==a.target&&R.Jd[b].Fd==a.Fd&&tb(b--);return 0}
function yb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var R={We:0,fe:0,he:0,be:0,te:0,qe:0,de:0,$e:0,ff:0,Ze:0,ee:0,ie:0,se:0,pe:0,gf(){for(;R.Jd.length;)tb(R.Jd.length-1);R.Rd=[]},ge:0,Rd:[],Jd:[],Se:(a,b)=>{for(var c=0;c<R.Jd.length;++c)R.Jd[c].target!=a||b&&b!=R.Jd[c].Fd||tb(c--)},hf(a){let b=!1;for(let c=0;c<R.Jd.length;++c){const d=R.Jd[c];d.target===a.target&&d.Kd===a.Kd&&d.Id===a.Id&&d.Nd===a.Nd&&(tb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},zb=[0,document,window],T=a=>
{a=2<a?a?x(w,a):"":a;return zb[a]||document.querySelector(a)},Bb=a=>{var b=Ya(a)+1,c=Ab(b);K(a,c,b);return c},Eb=a=>{var b=Cb(),c=Ab(8),d=c+4;a=Bb(a.id);if(a=T(a))p[c>>2]=a.width,p[d>>2]=a.height;c=[p[c>>2],p[d>>2]];Db(b);return c},Fb=(a,b,c)=>{a=T(a);if(!a)return-4;a.width=b;a.height=c;return 0},Gb=(a,b,c)=>{if(a.Xe){var d=Cb();a=Bb(a.id);Fb(a,b,c);Db(d)}else a.width=b,a.height=c},Hb={},Ib=a=>{function b(){ua()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Gb(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=u,a.style.paddingRight=F,a.style.paddingTop=L,a.style.paddingBottom=I,a.style.marginLeft=xc,a.style.marginRight=yc,a.style.marginTop=zc,a.style.marginBottom=Ac,document.body.style.margin=Bc,document.documentElement.style.overflow=Cc,document.body.scroll=Dc,a.style.Sd=Ec,a.Td&&a.Td.Qd.viewport(0,0,d,e),Hb.Wd&&U(Hb.Wd,37,0,
Hb.we))}var c=Eb(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,u=a.style.paddingLeft,F=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,xc=a.style.marginLeft,yc=a.style.marginRight,zc=a.style.marginTop,Ac=a.style.marginBottom,Bc=document.body.style.margin,Cc=document.documentElement.style.overflow,Dc=document.body.scroll,Ec=a.style.Sd;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Jb=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Kb=a=>0>zb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Lb=(a,b)=>{if(0!=b.je||0!=b.ce){Ib(a);var c=b.Te?innerWidth:screen.width,d=b.Te?innerHeight:screen.height,e=Kb(a),f=e.width;e=e.height;var g=Eb(a),l=g[0];g=g[1];3==b.je?(Jb(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.je&&(c*g<l*d?(f=g*c/l,Jb(a,(d-f)/2,0),d=f):(f=l*d/g,Jb(a,0,(c-f)/2),c=f));var m;(m=a.style).backgroundColor||(m.backgroundColor=
"black");let u;(u=document.body.style).backgroundColor||(u.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Oe&&(a.style.Sd="optimizeSpeed",a.style.Sd="-moz-crisp-edges",a.style.Sd="-o-crisp-edges",a.style.Sd="-webkit-optimize-contrast",a.style.Sd="optimize-contrast",a.style.Sd="crisp-edges",a.style.Sd="pixelated");m=2==b.ce?devicePixelRatio:1;0!=b.ce&&(c=c*m|0,d=d*m|0,Gb(a,c,d),a.Td&&a.Td.Qd.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return R.fullscreenEnabled()?-3:-1;Hb=b;b.Wd&&U(b.Wd,37,0,b.we);return 0},Mb=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Nb=[],Ob=(a,b,c,d,e,f,g,l)=>{b=C[b];if(a=B[a](b,c))d=l&&K(a.name,l,d),e&&(p[e>>2]=d),f&&(p[f>>2]=a.size),g&&(p[g>>2]=a.type)},Pb=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(J||=1280);return;case 36345:d=0;break;case 34466:var e=B.getParameter(34467);d=e?e.length:0}if(void 0===
d)switch(e=B.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":J||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:J||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:p[b+4*a>>2]=e[a];break;case 2:r[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=
e.name|0}catch(f){J||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:J||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:p[b>>2]=d;break;case 2:r[b>>2]=d;break;case 4:q[b]=d?1:0}}else J||=1281},Qb=(a,b,c)=>{if(c){a=B.Pd.getQueryObjectEXT(H[a],b);var d;"boolean"==
typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else J||=1281},Rb=(a,b,c)=>{if(c){a=B.Pd.getQueryObjectEXT(H[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;p[c>>2]=d}else J||=1281},Sb=()=>{var a=Ma(B);return a=a.concat(a.map(b=>"GL_"+b))},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{var b=a.Ud,c=a.De,d;if(!b){a.Ud=b={};a.Ce={};var e=B.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=B.getActiveUniform(a,d);var g=f.name;f=f.size;var l=Tb(g);l=0<l?g.slice(0,l):g;var m=a.re;a.re+=
f;c[l]=[f,m];for(g=0;g<f;++g)b[m]=g,a.Ce[m++]=l}}},V=a=>{var b=B.Ge;if(b){var c=b.Ud[a];"number"==typeof c&&(b.Ud[a]=c=B.getUniformLocation(b,b.Ce[a]+(0<c?`[${c}]`:"")));return c}J||=1282},Vb=(a,b,c,d)=>{if(c)if(a=C[a],Ub(a),a=B.getUniform(a,V(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:p[c>>2]=a;break;case 2:r[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:p[c+4*b>>2]=a[b];break;case 2:r[c+4*b>>2]=a[b]}else J||=1281},Wb=(a,b,c,d)=>{if(c)if(a=B.getVertexAttrib(a,b),34975==b)p[c>>
2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:p[c>>2]=a;break;case 2:r[c>>2]=a;break;case 5:p[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:p[c+4*b>>2]=a[b];break;case 2:r[c+4*b>>2]=a[b];break;case 5:p[c+4*b>>2]=Math.fround(a[b])}else J||=1281},Xb=(a,b,c,d,e)=>{a-=5120;a=1==a?w:4==a?p:6==a?r:5==a||28922==a?v:qa;b=d*((Ta||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Sa-1&-Sa);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=[],Yb=[],Zb=(a,b)=>{if(!R.fullscreenEnabled())return-1;a=T(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?wb()?Lb(a,b):b.Ke?(ub(Lb,1,[a,b]),1):-2:-3:-4},$b=(a,b)=>{var c={target:T(2),Fd:"beforeunload",Kd:28,Nd:a,Id:b,Od:d=>{var e=U(b,28,0,a);e&&=e?x(w,e):"";if(e)return d.preventDefault(),d.returnValue=e},Ld:!0};return S(c)},ac=(a,b,c,d,e,f)=>{R.de||(R.de=M(256));a={target:T(a),Fd:f,Kd:e,Nd:b,Id:d,Od:g=>{var l=g.target.id?g.target.id:"",m=R.de;
K(yb(g.target),m+0,128);K(l,m+128,128);U(d,e,m,b)&&g.preventDefault()},Ld:c};return S(a)},bc=(a,b,c,d,e)=>{R.ee||(R.ee=M(276));return S({target:a,Fd:e,Kd:19,Nd:b,Id:d,Od:f=>{var g=R.ee,l=ua(),m=!!l;q[g]=m;q[g+1]=R.fullscreenEnabled();var u=m?l:R.Re,F=u?.id||"";K(yb(u),g+2,128);K(F,g+130,128);p[g+260>>2]=u?u.clientWidth:0;p[g+264>>2]=u?u.clientHeight:0;p[g+268>>2]=screen.width;p[g+272>>2]=screen.height;m&&(R.Re=l);U(d,19,g,b)&&f.preventDefault()},Ld:c})},cc=(a,b,c,d,e)=>{R.fe||(R.fe=M(1240));b={target:T(2),
Vd:!0,Fd:e,Kd:d,Nd:a,Id:c,Od:f=>{var g=R.fe,l=f.gamepad;t[g>>3]=l.timestamp;for(var m=0;m<l.axes.length;++m)t[g+8*m+16>>3]=l.axes[m];for(m=0;m<l.buttons.length;++m)t[g+8*m+528>>3]="object"==typeof l.buttons[m]?l.buttons[m].value:l.buttons[m];for(m=0;m<l.buttons.length;++m)q[g+m+1040]="object"==typeof l.buttons[m]?l.buttons[m].pressed:1==l.buttons[m];q[g+1104]=l.connected;p[g+1108>>2]=l.index;p[g+8>>2]=l.axes.length;p[g+12>>2]=l.buttons.length;K(l.id,g+1112,64);K(l.mapping,g+1176,64);U(c,d,g,a)&&f.preventDefault()},
Ld:b};return S(b)},dc=()=>{try{if(navigator.getGamepads)return(R.bf=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},ec=(a,b,c,d,e,f)=>{R.he||(R.he=M(160));a={target:T(a),Fd:f,Kd:e,Nd:b,Id:d,Od:g=>{var l=R.he;t[l>>3]=g.timeStamp;var m=l>>2;p[m+2]=g.location;q[l+12]=g.ctrlKey;q[l+13]=g.shiftKey;q[l+14]=g.altKey;q[l+15]=g.metaKey;q[l+16]=g.repeat;p[m+5]=g.charCode;p[m+6]=g.keyCode;p[m+7]=g.which;K(g.key||"",l+32,32);K(g.code||"",l+64,32);K(g.char||"",l+96,32);K(g.locale||
"",l+128,32);U(d,e,l,b)&&g.preventDefault()},Ld:c};return S(a)},fc=(a,b,c)=>{t[a>>3]=b.timeStamp;var d=a>>2;p[d+2]=b.screenX;p[d+3]=b.screenY;p[d+4]=b.clientX;p[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;p[d+8]=b.movementX;p[d+9]=b.movementY;a=Kb(c);p[d+10]=b.clientX-(a.left|0);p[d+11]=b.clientY-(a.top|0)},gc=(a,b,c,d,e,f)=>{R.be||(R.be=M(64));a=T(a);return S({target:a,Vd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=
f,Fd:f,Kd:e,Nd:b,Id:d,Od:g=>{fc(R.be,g,a);U(d,e,R.be,b)&&g.preventDefault()},Ld:c})},hc=(a,b,c,d)=>{R.ie||(R.ie=M(257));return S({target:a,Fd:"pointerlockchange",Kd:20,Nd:b,Id:d,Od:e=>{var f=R.ie,g=document.pointerLockElement;q[f]=!!g;var l=g?.id||"";K(yb(g),f+1,128);K(l,f+129,128);U(d,20,f,b)&&e.preventDefault()},Ld:c})},ic=(a,b,c,d)=>{R.qe||(R.qe=M(36));a=T(a);return S({target:a,Fd:"resize",Kd:10,Nd:b,Id:d,Od:e=>{if(e.target==a){var f=document.body;if(f){var g=R.qe;p[g>>2]=0;p[g+4>>2]=f.clientWidth;
p[g+8>>2]=f.clientHeight;p[g+12>>2]=innerWidth;p[g+16>>2]=innerHeight;p[g+20>>2]=outerWidth;p[g+24>>2]=outerHeight;p[g+28>>2]=pageXOffset|0;p[g+32>>2]=pageYOffset|0;U(d,10,g,b)&&e.preventDefault()}}},Ld:c})},jc=(a,b,c,d,e,f)=>{R.pe||(R.pe=M(1552));a=T(a);return S({target:a,Vd:"touchstart"==f||"touchend"==f,Fd:f,Kd:e,Nd:b,Id:d,Od:g=>{var l={},m=g.touches;for(var u of m)u.ye=u.Ae=0,l[u.identifier]=u;for(var F of g.changedTouches)F.ye=1,l[F.identifier]=F;for(var L of g.targetTouches)l[L.identifier].Ae=
1;m=R.pe;t[m>>3]=g.timeStamp;q[m+12]=g.ctrlKey;q[m+13]=g.shiftKey;q[m+14]=g.altKey;q[m+15]=g.metaKey;u=m+16;F=Kb(a);L=0;for(let I of Object.values(l))if(l=u>>2,p[l]=I.identifier,p[l+1]=I.screenX,p[l+2]=I.screenY,p[l+3]=I.clientX,p[l+4]=I.clientY,p[l+5]=I.pageX,p[l+6]=I.pageY,q[u+28]=I.ye,q[u+29]=I.Ae,p[l+8]=I.clientX-(F.left|0),p[l+9]=I.clientY-(F.top|0),u+=48,31<++L)break;p[m+8>>2]=L;U(d,e,m,b)&&g.preventDefault()},Ld:c})},kc=(a,b,c)=>{var d=zb[1];R.se||(R.se=M(8));return S({target:d,Fd:"visibilitychange",
Kd:21,Nd:a,Id:c,Od:e=>{var f=R.se,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[f]=document.hidden;p[f+4>>2]=g;U(c,21,f,a)&&e.preventDefault()},Ld:b})},lc=(a,b,c,d)=>{R.te||(R.te=M(96));return S({target:a,Vd:!0,Fd:"wheel",Kd:9,Nd:b,Id:d,Od:e=>{var f=R.te;fc(f,e,a);t[f+64>>3]=e.deltaX;t[f+72>>3]=e.deltaY;t[f+80>>3]=e.deltaZ;p[f+88>>2]=e.deltaMode;U(d,9,f,b)&&e.preventDefault()},Ld:c})},mc={},oc=()=>{if(!nc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",
HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in mc)void 0===mc[b]?delete a[b]:a[b]=mc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nc=c}return nc},nc,pc=[null,[],[]],qc=a=>{try{a()}catch(b){ia(b)}};function rc(a){var b=(...c)=>{sc.push(a);try{return a(...c)}finally{n||(sc.pop(),X&&1===Y&&0===sc.length&&(Y=0,qc(tc),"undefined"!=typeof Fibers&&Fibers.kf()))}};uc.set(a,b);return b}
var Y=0,X=null,vc=0,sc=[],wc=new Map,Fc=new Map,uc=new Map,Gc=0,Hc=null,Ic=[];function Jc(){var a=M(4108),b=a+12;v[a>>2]=b;v[a+4>>2]=b+4096;b=sc[0];if(!wc.has(b)){var c=Gc++;wc.set(b,c);Fc.set(c,b)}b=wc.get(b);p[a+8>>2]=b;return a}function Kc(){var a=Fc.get(p[X+8>>2]);a=uc.get(a);return ta(a)}
function Lc(a){if(!n){if(0===Y){var b=!1,c=!1;a((d=0)=>{if(!n&&(vc=d,b=!0,c)){Y=2;qc(()=>Mc(X));"undefined"!=typeof pb&&O&&mb();d=!1;try{var e=Kc()}catch(l){e=l,d=!0}var f=!1;if(!X){var g=Hc;g&&(Hc=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Y=1,X=Jc(),"undefined"!=typeof pb&&O&&lb(),qc(()=>Nc(X)))}else 2===Y?(Y=0,qc(Oc),Pc(X),X=null,Ic.forEach(ta)):ia(`invalid state: ${Y}`);return vc}}var Qc=a=>Lc(async b=>{b(await a())});h.requestAnimationFrame=ob;h.pauseMainLoop=lb;
h.resumeMainLoop=mb;for(let a=0;32>a;++a)Nb.push(Array(a));for(var Rc=new Float32Array(288),Z=0;288>=Z;++Z)W[Z]=Rc.subarray(0,Z);var Sc=new Int32Array(288);for(Z=0;288>=Z;++Z)Yb[Z]=Sc.subarray(0,Z);h.createContext=za;
var Tc={53132:a=>{a=(a?x(w,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return 1===a.length?a.charCodeAt(0):-1},53347:()=>window.innerWidth,53377:()=>window.innerHeight,53408:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Ee!==h.canvas&&(d.Yd=za(h.canvas,!1,!0),d.Ee=h.canvas);if(d.w!==a||d.h!==b||d.Pe!==d.Yd)d.image=d.Yd.createImageData(a,b),d.w=a,d.h=b,d.Pe=d.Yd;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=
a.length;e<c;){var f=p[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Ie!==a&&(d.He=new Int32Array(a.buffer),d.Je=new Uint8Array(a.buffer),d.Ie=a),a=d.He,c=a.length,a.set(p.subarray(b,b+c)),a=d.Je,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Yd.putImageData(d.image,0,0)},54874:(a,b,c,d,e)=>{var f=document.createElement("canvas");
f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,m;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(m=b.length;l<m;){var u=p[e];b[l]=u&255;b[l+1]=u>>8&255;b[l+2]=u>>16&255;b[l+3]=u>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(p.subarray(e,e+m));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=M(c.length+1);K(c,d,c.length+1);return d},55862:a=>
{h.canvas&&(h.canvas.style.cursor=a?x(w,a):"")},55945:()=>{h.canvas&&(h.canvas.style.cursor="none")}},M,Pc,Uc,Db,Ab,Cb,dynCall_vi,dynCall_iii,U,dynCall_vii,dynCall_v,Nc,tc,Mc,Oc,Vc,Wc={jb:(a,b)=>dynCall_vi(a,b),j:function(){return 0},sb:function(){return 0},tb:function(){},vb:()=>ia(""),lb:()=>{},hb:(a,b)=>{sa[a]&&(clearTimeout(sa[a].id),delete sa[a]);if(!b)return 0;var c=setTimeout(()=>{delete sa[a];ta(()=>Uc(a,performance.now()))},b);sa[a]={id:c,jf:b};return 0},Jb:a=>{if(12448==a)return z=12288,
1;z=12300;return 0},Vb:(a,b,c,d,e)=>{if(62E3!=a)z=12296,c=0;else{if(b)for(;;){a=p[b>>2];if(12321==a)A.alpha=0<p[b+4>>2];else if(12325==a)A.depth=0<p[b+4>>2];else if(12326==a)A.stencil=0<p[b+4>>2];else if(12337==a)a=p[b+4>>2],A.antialias=0<a;else if(12338==a)a=p[b+4>>2],A.antialias=1==a;else if(12544==a)A.cf=12547!=p[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(p[e>>2]=1),c&&0<d&&(v[c>>2]=62002),z=12288,c=1):(z=12300,c=0)}return c},Tb:(a,b,c,d)=>{if(62E3!=a)return z=12296,0;for(a=1;;){b=p[d>>2];
if(12440==b)a=p[d+4>>2];else if(12344==b)break;else return z=12292,0;d+=8}if(2!=a)return z=12293,0;A.ze=a-1;A.df=0;Ia=Ba(h.canvas,A);if(0!=Ia)return z=12288,Ca(Ia),wa.forEach(e=>e()),Ca(null),62004;z=12297;return 0},Qb:(a,b)=>{if(62E3!=a)return z=12296,0;if(62002!=b)return z=12293,0;z=12288;return 62006},Sb:(a,b)=>{if(62E3!=a)return z=12296,0;if(62004!=b)return z=12294,0;a=Ia;Xa===y[a]&&(Xa=null);"object"==typeof R&&R.Se(y[a].Qd.canvas);y[a]?.Qd.canvas&&(y[a].Qd.canvas.Td=void 0);y[a]=null;z=12288;
Ea==b&&(Ea=0);return 1},Pb:(a,b)=>{if(62E3!=a)return z=12296,0;if(62006!=b)return z=12301,1;Fa==b&&(Fa=0);Ga==b&&(Ga=0);z=12288;return 1},Ub:(a,b,c,d)=>{if(62E3!=a)return z=12296,0;if(62002!=b)return z=12293,0;if(!d)return z=12300,0;z=12288;switch(c){case 12320:return p[d>>2]=A.alpha?32:24,1;case 12321:return p[d>>2]=A.alpha?8:0,1;case 12322:return p[d>>2]=8,1;case 12323:return p[d>>2]=8,1;case 12324:return p[d>>2]=8,1;case 12325:return p[d>>2]=A.depth?24:0,1;case 12326:return p[d>>2]=A.stencil?8:
0,1;case 12327:return p[d>>2]=12344,1;case 12328:return p[d>>2]=62002,1;case 12329:return p[d>>2]=0,1;case 12330:return p[d>>2]=4096,1;case 12331:return p[d>>2]=16777216,1;case 12332:return p[d>>2]=4096,1;case 12333:return p[d>>2]=0,1;case 12334:return p[d>>2]=0,1;case 12335:return p[d>>2]=12344,1;case 12337:return p[d>>2]=A.antialias?4:0,1;case 12338:return p[d>>2]=A.antialias?1:0,1;case 12339:return p[d>>2]=4,1;case 12340:return p[d>>2]=12344,1;case 12341:case 12342:case 12343:return p[d>>2]=-1,
1;case 12345:case 12346:return p[d>>2]=0,1;case 12347:return p[d>>2]=0,1;case 12348:return p[d>>2]=1;case 12349:case 12350:return p[d>>2]=0,1;case 12351:return p[d>>2]=12430,1;case 12352:return p[d>>2]=4,1;case 12354:return p[d>>2]=0,1;default:return z=12292,0}},F:a=>{z=12288;return 0!=a&&1!=a?0:62E3},Hb:()=>z,Xb:(a,b,c)=>{if(62E3!=a)return z=12296,0;b&&(p[b>>2]=1);c&&(p[c>>2]=4);Da=!0;z=12288;return 1},Ob:(a,b,c,d)=>{if(62E3!=a)return z=12296,0;if(0!=d&&62004!=d)return z=12294,0;if(0!=c&&62006!=
c||0!=b&&62006!=b)return z=12301,0;Ca(d?Ia:null);Ea=d;Ga=b;Fa=c;z=12288;return 1},Ib:(a,b)=>{if(62E3!=a)return z=12296,0;z=12288;if(Ha[b])return Ha[b];switch(b){case 12371:a=N("Emscripten");break;case 12372:a=N("1.4 Emscripten EGL");break;case 12373:a=N("");break;case 12429:a=N("OpenGL_ES");break;default:return z=12300,0}return Ha[b]=a},Nb:()=>{if(Da)if(B)if(B.isContextLost())z=12302;else return z=12288,1;else z=12290;else z=12289;return 0},Mb:(a,b)=>{if(62E3!=a)return z=12296,0;0==b?jb(0,0):jb(1,
b);z=12288;return 1},Wb:a=>{if(62E3!=a)return z=12296,0;Ga=Fa=Ea=0;Da=!1;z=12288;return 1},Kb:()=>{z=12288;return 1},Lb:()=>{z=12288;return 1},b:(a,b,c)=>{b=sb(b,c);return Tc[a](...b)},Eb:(a,b,c)=>{b=sb(b,c);return Tc[a](...b)},G:()=>{lb();O=null},ub:()=>Date.now(),wb:()=>{if(!R.fullscreenEnabled())return-1;vb(Lb);var a=zb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Db:()=>
{vb(Mb);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},ab:a=>{throw new na(a);},d:()=>devicePixelRatio,a:(a,b,c)=>{a=T(a);if(!a)return-4;a=Kb(a);t[b>>3]=a.width;t[c>>3]=a.height;return 0},e:()=>performance.now(),Fb:(a,b)=>{p[a>>2]=screen.width;p[b>>2]=screen.height},gb:a=>B.activeTexture(a),fb:(a,b)=>{B.attachShader(C[a],G[b])},aa:(a,b)=>{B.Pd.beginQueryEXT(a,H[b])},eb:(a,b,c)=>{B.bindAttribLocation(C[a],b,c?x(w,c):"")},db:(a,b)=>{B.bindBuffer(a,Oa[b])},cb:(a,b)=>{B.bindFramebuffer(a,
Pa[b])},bb:(a,b)=>{B.bindRenderbuffer(a,D[b])},$a:(a,b)=>{B.bindTexture(a,E[b])},ic:a=>{B.bindVertexArray(Qa[a])},_a:(a,b,c,d)=>B.blendColor(a,b,c,d),Za:a=>B.blendEquation(a),Ya:(a,b)=>B.blendEquationSeparate(a,b),Xa:(a,b)=>B.blendFunc(a,b),Wa:(a,b,c,d)=>B.blendFuncSeparate(a,b,c,d),Va:(a,b,c,d)=>{B.bufferData(a,c?w.subarray(c,c+b):b,d)},Ua:(a,b,c,d)=>{B.bufferSubData(a,b,w.subarray(d,d+c))},Ta:a=>B.checkFramebufferStatus(a),Sa:a=>B.clear(a),Ra:(a,b,c,d)=>B.clearColor(a,b,c,d),Qa:a=>B.clearDepth(a),
Pa:a=>B.clearStencil(a),ac:(a,b)=>{B.Me.clipControlEXT(a,b)},Oa:(a,b,c,d)=>{B.colorMask(!!a,!!b,!!c,!!d)},Na:a=>{B.compileShader(G[a])},Ma:(a,b,c,d,e,f,g,l)=>{B.compressedTexImage2D(a,b,c,d,e,f,w.subarray(l,l+g))},La:(a,b,c,d,e,f,g,l,m)=>{B.compressedTexSubImage2D(a,b,c,d,e,f,g,w.subarray(m,m+l))},Ka:(a,b,c,d,e,f,g,l)=>B.copyTexImage2D(a,b,c,d,e,f,g,l),Ja:(a,b,c,d,e,f,g,l)=>B.copyTexSubImage2D(a,b,c,d,e,f,g,l),Ia:()=>{var a=Ua(C),b=B.createProgram();b.name=a;b.ae=b.Zd=b.$d=0;b.re=1;C[a]=b;return a},
Ga:a=>{var b=Ua(G);G[b]=B.createShader(a);return b},Fa:a=>B.cullFace(a),Ea:(a,b)=>{for(var c=0;c<a;c++){var d=p[b+4*c>>2],e=Oa[d];e&&(B.deleteBuffer(e),e.name=0,Oa[d]=null)}},Da:(a,b)=>{for(var c=0;c<a;++c){var d=p[b+4*c>>2],e=Pa[d];e&&(B.deleteFramebuffer(e),e.name=0,Pa[d]=null)}},Ca:a=>{if(a){var b=C[a];b?(B.deleteProgram(b),b.name=0,C[a]=null):J||=1281}},wa:(a,b)=>{for(var c=0;c<a;c++){var d=p[b+4*c>>2],e=H[d];e&&(B.Pd.deleteQueryEXT(e),H[d]=null)}},Ba:(a,b)=>{for(var c=0;c<a;c++){var d=p[b+4*
c>>2],e=D[d];e&&(B.deleteRenderbuffer(e),e.name=0,D[d]=null)}},Aa:a=>{if(a){var b=G[a];b?(B.deleteShader(b),G[a]=null):J||=1281}},za:(a,b)=>{for(var c=0;c<a;c++){var d=p[b+4*c>>2],e=E[d];e&&(B.deleteTexture(e),e.name=0,E[d]=null)}},Zb:(a,b)=>{for(var c=0;c<a;c++){var d=p[b+4*c>>2];B.deleteVertexArray(Qa[d]);Qa[d]=null}},ya:a=>B.depthFunc(a),xa:a=>{B.depthMask(!!a)},va:(a,b)=>B.depthRange(a,b),ua:(a,b)=>{B.detachShader(C[a],G[b])},ta:a=>B.disable(a),sa:a=>{B.disableVertexAttribArray(a)},ra:(a,b,c)=>
{B.drawArrays(a,b,c)},Ab:(a,b,c,d)=>{B.drawArraysInstanced(a,b,c,d)},Bb:(a,b)=>{for(var c=Nb[a],d=0;d<a;d++)c[d]=p[b+4*d>>2];B.drawBuffers(c)},qa:(a,b,c,d)=>{B.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{B.drawElementsInstanced(a,b,c,d,e)},pa:a=>B.enable(a),oa:a=>{B.enableVertexAttribArray(a)},R:a=>{B.Pd.endQueryEXT(a)},na:()=>B.finish(),ma:()=>B.flush(),ka:(a,b,c,d)=>{B.framebufferRenderbuffer(a,b,c,D[d])},ja:(a,b,c,d,e)=>{B.framebufferTexture2D(a,b,c,E[d],e)},ia:a=>B.frontFace(a),ha:(a,b)=>{Va(a,b,
"createBuffer",Oa)},fa:(a,b)=>{Va(a,b,"createFramebuffer",Pa)},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=B.Pd.createQueryEXT();if(!d){for(J||=1282;c<a;)p[b+4*c++>>2]=0;break}var e=Ua(H);d.name=e;H[e]=d;p[b+4*c>>2]=e}},ea:(a,b)=>{Va(a,b,"createRenderbuffer",D)},da:(a,b)=>{Va(a,b,"createTexture",E)},Rb:(a,b)=>{Va(a,b,"createVertexArray",Qa)},ga:a=>B.generateMipmap(a),ca:(a,b,c,d,e,f,g)=>Ob("getActiveAttrib",a,b,c,d,e,f,g),ba:(a,b,c,d,e,f,g)=>Ob("getActiveUniform",a,b,c,d,e,f,g),$:(a,b,c,d)=>{a=B.getAttachedShaders(C[a]);
var e=a.length;e>b&&(e=b);p[c>>2]=e;for(b=0;b<e;++b)p[d+4*b>>2]=G.indexOf(a[b])},_:(a,b)=>B.getAttribLocation(C[a],b?x(w,b):""),Z:(a,b)=>Pb(a,b,4),Y:(a,b,c)=>{c?p[c>>2]=B.getBufferParameter(a,b):J||=1281},X:()=>{var a=B.getError()||J;J=0;return a},W:(a,b)=>Pb(a,b,2),V:(a,b,c,d)=>{a=B.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;p[d>>2]=a},U:(a,b)=>Pb(a,b,0),S:(a,b,c,d)=>{a=B.getProgramInfoLog(C[a]);null===a&&(a="(unknown error)");
b=0<b&&d?K(a,d,b):0;c&&(p[c>>2]=b)},T:(a,b,c)=>{if(c)if(a>=Na)J||=1281;else if(a=C[a],35716==b)a=B.getProgramInfoLog(a),null===a&&(a="(unknown error)"),p[c>>2]=a.length+1;else if(35719==b){if(!a.ae){var d=B.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ae=Math.max(a.ae,B.getActiveUniform(a,b).name.length+1)}p[c>>2]=a.ae}else if(35722==b){if(!a.Zd)for(d=B.getProgramParameter(a,35721),b=0;b<d;++b)a.Zd=Math.max(a.Zd,B.getActiveAttrib(a,b).name.length+1);p[c>>2]=a.Zd}else if(35381==b){if(!a.$d)for(d=
B.getProgramParameter(a,35382),b=0;b<d;++b)a.$d=Math.max(a.$d,B.getActiveUniformBlockName(a,b).length+1);p[c>>2]=a.$d}else p[c>>2]=B.getProgramParameter(a,b);else J||=1281},Ec:Qb,_c:Rb,tc:Qb,Pc:Rb,jd:(a,b,c)=>{c?p[c>>2]=B.Pd.getQueryEXT(a,b):J||=1281},Q:(a,b,c)=>{c?p[c>>2]=B.getRenderbufferParameter(a,b):J||=1281},O:(a,b,c,d)=>{a=B.getShaderInfoLog(G[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(p[c>>2]=b)},N:(a,b,c,d)=>{a=B.getShaderPrecisionFormat(a,b);p[c>>2]=a.rangeMin;p[c+4>>2]=
a.rangeMax;p[d>>2]=a.precision},M:(a,b,c,d)=>{if(a=B.getShaderSource(G[a]))b=0<b&&d?K(a,d,b):0,c&&(p[c>>2]=b)},P:(a,b,c)=>{c?35716==b?(a=B.getShaderInfoLog(G[a]),null===a&&(a="(unknown error)"),p[c>>2]=a?a.length+1:0):35720==b?(a=B.getShaderSource(G[a]),p[c>>2]=a?a.length+1:0):p[c>>2]=B.getShaderParameter(G[a],b):J||=1281},L:a=>{var b=Ra[a];if(!b){switch(a){case 7939:b=N(Sb().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=B.getParameter(a))||(J||=1280);b=b?N(b):0;break;case 7938:b=
N(`OpenGL ES 2.0 (${B.getParameter(7938)})`);break;case 35724:b=B.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=N(b);break;default:J||=1280}Ra[a]=b}return b},K:(a,b,c)=>{c?r[c>>2]=B.getTexParameter(a,b):J||=1281},J:(a,b,c)=>{c?p[c>>2]=B.getTexParameter(a,b):J||=1281},td:(a,b)=>{b=b?x(w,b):"";if(a=C[a]){Ub(a);var c=a.Ud,d=0,e=b,f=Tb(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));
if((e=a.De[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||B.getUniformLocation(a,b)))return d}else J||=1281;return-1},I:(a,b,c)=>{Vb(a,b,c,2)},H:(a,b,c)=>{Vb(a,b,c,0)},qd:(a,b,c)=>{c?p[c>>2]=B.getVertexAttribOffset(a,b):J||=1281},sd:(a,b,c)=>{Wb(a,b,c,2)},rd:(a,b,c)=>{Wb(a,b,c,5)},pd:(a,b)=>B.hint(a,b),od:a=>(a=Oa[a])?B.isBuffer(a):0,nd:a=>B.isEnabled(a),md:a=>(a=Pa[a])?B.isFramebuffer(a):0,ld:a=>(a=C[a])?B.isProgram(a):0,la:a=>(a=H[a])?B.Pd.isQueryEXT(a):0,kd:a=>(a=D[a])?B.isRenderbuffer(a):0,id:a=>(a=G[a])?B.isShader(a):
0,hd:a=>(a=E[a])?B.isTexture(a):0,Gb:a=>(a=Qa[a])?B.isVertexArray(a):0,gd:a=>B.lineWidth(a),fd:a=>{a=C[a];B.linkProgram(a);a.Ud=0;a.De={}},ed:(a,b)=>{3317==a?Sa=b:3314==a&&(Ta=b);B.pixelStorei(a,b)},$b:(a,b)=>{B.Ue.polygonModeWEBGL(a,b)},dd:(a,b)=>B.polygonOffset(a,b),bc:(a,b,c)=>{B.Ne.polygonOffsetClampEXT(a,b,c)},ud:(a,b)=>{B.Pd.queryCounterEXT(H[a],b)},cd:(a,b,c,d,e,f,g)=>{(g=Xb(f,e,c,d,g))?B.readPixels(a,b,c,d,e,f,g):J||=1280},bd:()=>{},ad:(a,b,c,d)=>B.renderbufferStorage(a,b,c,d),$c:(a,b)=>{B.sampleCoverage(a,
!!b)},Zc:(a,b,c,d)=>B.scissor(a,b,c,d),Yc:()=>{J||=1280},Xc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?x(w,g,d?v[d+4*f>>2]:void 0):"";e+=g}B.shaderSource(G[a],e)},Wc:(a,b,c)=>B.stencilFunc(a,b,c),Vc:(a,b,c,d)=>B.stencilFuncSeparate(a,b,c,d),Uc:a=>B.stencilMask(a),Tc:(a,b)=>B.stencilMaskSeparate(a,b),Sc:(a,b,c)=>B.stencilOp(a,b,c),Rc:(a,b,c,d)=>B.stencilOpSeparate(a,b,c,d),Qc:(a,b,c,d,e,f,g,l,m)=>{m=m?Xb(l,g,d,e,m):null;B.texImage2D(a,b,c,d,e,f,g,l,m)},Oc:(a,b,c)=>B.texParameterf(a,
b,c),Nc:(a,b,c)=>{B.texParameterf(a,b,r[c>>2])},Mc:(a,b,c)=>B.texParameteri(a,b,c),Lc:(a,b,c)=>{B.texParameteri(a,b,p[c>>2])},Kc:(a,b,c,d,e,f,g,l,m)=>{m=m?Xb(l,g,e,f,m):null;B.texSubImage2D(a,b,c,d,e,f,g,l,m)},Jc:(a,b)=>{B.uniform1f(V(a),b)},Ic:(a,b,c)=>{if(288>=b)for(var d=W[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);B.uniform1fv(V(a),d)},Hc:(a,b)=>{B.uniform1i(V(a),b)},Gc:(a,b,c)=>{if(288>=b)for(var d=Yb[b],e=0;e<b;++e)d[e]=p[c+4*e>>2];else d=p.subarray(c>>2,c+4*b>>2);B.uniform1iv(V(a),
d)},Fc:(a,b,c)=>{B.uniform2f(V(a),b,c)},Dc:(a,b,c)=>{if(144>=b){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);B.uniform2fv(V(a),d)},Cc:(a,b,c)=>{B.uniform2i(V(a),b,c)},Bc:(a,b,c)=>{if(144>=b){b*=2;for(var d=Yb[b],e=0;e<b;e+=2)d[e]=p[c+4*e>>2],d[e+1]=p[c+(4*e+4)>>2]}else d=p.subarray(c>>2,c+8*b>>2);B.uniform2iv(V(a),d)},Ac:(a,b,c,d)=>{B.uniform3f(V(a),b,c,d)},zc:(a,b,c)=>{if(96>=b){b*=3;for(var d=W[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=
r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);B.uniform3fv(V(a),d)},yc:(a,b,c,d)=>{B.uniform3i(V(a),b,c,d)},xc:(a,b,c)=>{if(96>=b){b*=3;for(var d=Yb[b],e=0;e<b;e+=3)d[e]=p[c+4*e>>2],d[e+1]=p[c+(4*e+4)>>2],d[e+2]=p[c+(4*e+8)>>2]}else d=p.subarray(c>>2,c+12*b>>2);B.uniform3iv(V(a),d)},wc:(a,b,c,d,e)=>{B.uniform4f(V(a),b,c,d,e)},vc:(a,b,c)=>{if(72>=b){var d=W[4*b],e=r;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=r.subarray(c>>
2,c+16*b>>2);B.uniform4fv(V(a),d)},uc:(a,b,c,d,e)=>{B.uniform4i(V(a),b,c,d,e)},sc:(a,b,c)=>{if(72>=b){b*=4;for(var d=Yb[b],e=0;e<b;e+=4)d[e]=p[c+4*e>>2],d[e+1]=p[c+(4*e+4)>>2],d[e+2]=p[c+(4*e+8)>>2],d[e+3]=p[c+(4*e+12)>>2]}else d=p.subarray(c>>2,c+16*b>>2);B.uniform4iv(V(a),d)},rc:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=W[b],f=0;f<b;f+=4)e[f]=r[d+4*f>>2],e[f+1]=r[d+(4*f+4)>>2],e[f+2]=r[d+(4*f+8)>>2],e[f+3]=r[d+(4*f+12)>>2]}else e=r.subarray(d>>2,d+16*b>>2);B.uniformMatrix2fv(V(a),!!c,e)},qc:(a,b,c,d)=>
{if(32>=b){b*=9;for(var e=W[b],f=0;f<b;f+=9)e[f]=r[d+4*f>>2],e[f+1]=r[d+(4*f+4)>>2],e[f+2]=r[d+(4*f+8)>>2],e[f+3]=r[d+(4*f+12)>>2],e[f+4]=r[d+(4*f+16)>>2],e[f+5]=r[d+(4*f+20)>>2],e[f+6]=r[d+(4*f+24)>>2],e[f+7]=r[d+(4*f+28)>>2],e[f+8]=r[d+(4*f+32)>>2]}else e=r.subarray(d>>2,d+36*b>>2);B.uniformMatrix3fv(V(a),!!c,e)},pc:(a,b,c,d)=>{if(18>=b){var e=W[16*b],f=r;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+
7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=r.subarray(d>>2,d+64*b>>2);B.uniformMatrix4fv(V(a),!!c,e)},oc:a=>{a=C[a];B.useProgram(a);B.Ge=a},nc:a=>{B.validateProgram(C[a])},mc:(a,b)=>B.vertexAttrib1f(a,b),lc:(a,b)=>{B.vertexAttrib1f(a,r[b>>2])},kc:(a,b,c)=>B.vertexAttrib2f(a,b,c),jc:(a,b)=>{B.vertexAttrib2f(a,r[b>>2],r[b+4>>2])},hc:(a,b,c,d)=>B.vertexAttrib3f(a,b,c,d),gc:(a,b)=>{B.vertexAttrib3f(a,r[b>>
2],r[b+4>>2],r[b+8>>2])},fc:(a,b,c,d,e)=>B.vertexAttrib4f(a,b,c,d,e),ec:(a,b)=>{B.vertexAttrib4f(a,r[b>>2],r[b+4>>2],r[b+8>>2],r[b+12>>2])},ob:(a,b)=>{B.vertexAttribDivisor(a,b)},dc:(a,b,c,d,e,f)=>{B.vertexAttribPointer(a,b,c,!!d,e,f)},cc:(a,b,c,d)=>B.viewport(a,b,c,d),h:()=>1,yb:(a,b,c)=>Zb(a,{je:p[c>>2],ce:p[c+4>>2],Oe:p[c+8>>2],Ke:b,Wd:p[c+12>>2],we:p[c+16>>2]}),E:(a,b)=>{a=T(a);return a?a.requestPointerLock?wb()?Mb(a):b?(ub(Mb,2,[a]),1):-2:-1:-4},ib:()=>{ia("OOM")},k:(a,b,c)=>"undefined"==typeof onbeforeunload?
-1:1!==c?-5:$b(a,b),w:(a,b,c,d)=>ac(a,b,c,d,12,"blur"),c:Fb,f:(a,b,c)=>{a=T(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},x:(a,b,c,d)=>ac(a,b,c,d,13,"focus"),n:(a,b,c,d)=>{if(!R.fullscreenEnabled())return-1;a=T(a);if(!a)return-4;bc(a,b,c,d,"webkitfullscreenchange");return bc(a,b,c,d,"fullscreenchange")},_b:(a,b,c)=>dc()?-1:cc(a,b,c,26,"gamepadconnected"),Yb:(a,b,c)=>dc()?-1:cc(a,b,c,27,"gamepaddisconnected"),q:(a,b,c,d)=>ec(a,b,c,d,2,"keydown"),o:(a,b,c,d)=>ec(a,b,c,d,1,"keypress"),
p:(a,b,c,d)=>ec(a,b,c,d,3,"keyup"),Cb:(a,b,c,d)=>{kb(()=>dynCall_vi(a,b),c,d,b)},C:(a,b,c,d)=>gc(a,b,c,d,5,"mousedown"),A:(a,b,c,d)=>gc(a,b,c,d,33,"mouseenter"),z:(a,b,c,d)=>gc(a,b,c,d,34,"mouseleave"),D:(a,b,c,d)=>gc(a,b,c,d,8,"mousemove"),B:(a,b,c,d)=>gc(a,b,c,d,6,"mouseup"),r:(a,b,c,d)=>document.body?.requestPointerLock?(a=T(a))?hc(a,b,c,d):-4:-1,m:(a,b,c,d)=>ic(a,b,c,d),s:(a,b,c,d)=>jc(a,b,c,d,25,"touchcancel"),u:(a,b,c,d)=>jc(a,b,c,d,23,"touchend"),t:(a,b,c,d)=>jc(a,b,c,d,24,"touchmove"),v:(a,
b,c,d)=>jc(a,b,c,d,22,"touchstart"),l:(a,b,c)=>kc(a,b,c),y:(a,b,c,d)=>(a=T(a))?"undefined"!=typeof a.onwheel?lc(a,b,c,d):-1:-4,zb:a=>document.title=a?x(w,a):"",g:function(a){return Qc(()=>new Promise(b=>setTimeout(b,a)))},nb:(a,b)=>{var c=0,d=0,e;for(e of oc()){var f=b+c;v[a+d>>2]=f;c+=K(e,f,Infinity)+1;d+=4}return 0},pb:(a,b)=>{var c=oc();v[a>>2]=c.length;a=0;for(var d of c)a+=Ya(d)+1;v[b>>2]=a;return 0},i:()=>52,rb:()=>52,mb:function(){return 70},qb:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>
2],l=v[b+4>>2];b+=8;for(var m=0;m<l;m++){var u=a,F=w[g+m],L=pc[u];0===F||10===F?((1===u?da:k)(x(L)),L.length=0):L.push(F)}e+=l}v[d>>2]=e;return 0},kb:a=>{throw new na(a);}},Xc;
Xc=await (async function(){var a={a:Wc};ja??=h.locateFile?ba+"trmn-wasm.wasm":(new URL("trmn-wasm.wasm",import.meta.url)).href;var b=Xc=(await ma(a)).instance.exports;a={};for(let [c,d]of Object.entries(b))"function"==typeof d?(b=rc(d),a[c]=b):a[c]=d;a=Xc=a;h._playTromino=a.xd;M=a.yd;Pc=a.zd;Uc=a.Ad;Db=a.Bd;Ab=a.Cd;Cb=a.Dd;dynCall_vi=a.Ed;dynCall_iii=a.Gd;U=a.Hd;dynCall_vii=a.Md;dynCall_v=a.Xd;Nc=a.le;tc=a.me;Mc=a.ne;Oc=a.oe;Vc=a.vd;a=Vc.buffer;q=new Int8Array(a);oa=new Int16Array(a);
w=new Uint8Array(a);qa=new Uint16Array(a);p=new Int32Array(a);v=new Uint32Array(a);r=new Float32Array(a);t=new Float64Array(a);pa=new BigInt64Array(a);new BigUint64Array(a);return Xc}());h.calledRun=!0;n||(ha=!0,Xc.wd(),ea?.(h));ha?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ea=a;fa=b});
;return moduleRtn}export default createTrmnMod;
