
var createTrmnMod = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(moduleArg = {}) {

var h=moduleArg,aa,ba;h.ready=new Promise((a,b)=>{aa=a;ba=b});var ca=Object.assign({},h),k="";"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);_scriptDir&&(k=_scriptDir);0!==k.indexOf("blob:")?k=k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):k="";var da=console.log.bind(console),l=console.error.bind(console);Object.assign(h,ca);ca=null;"object"!=typeof WebAssembly&&p("no native wasm support detected");
var ea,q=!1,fa,r,ja,ka,u,x,y,z,la=[],ma=[],na=[],oa=[],pa=0,qa=null,ra=null;function p(a){a="Aborted("+a+")";l(a);q=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var sa=a=>a.startsWith("data:application/octet-stream;base64,"),ta;ta="trmn-wasm.wasm";sa(ta)||(ta=k+ta);function ua(){throw"both async and sync fetching of the wasm failed";}
function va(a){return"function"==typeof fetch?fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ua()):Promise.resolve().then(()=>ua())}function wa(a,b,c){return va(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);p(d)})}
function xa(a,b){var c=ta;return"function"!=typeof WebAssembly.instantiateStreaming||sa(c)||"function"!=typeof fetch?wa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return wa(c,a,b)}))}
var Ba={59092:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,59239:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,59473:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.yd||("undefined"!==typeof AudioContext?b.yd=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.yd=new webkitAudioContext),b.yd&&ya(b.yd));
return void 0===b.yd?-1:0},59966:()=>h.SDL2.yd.sampleRate,60034:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.xe&&(clearTimeout(g.capture.xe),g.capture.xe=void 0);g.capture.De=g.yd.createMediaStreamSource(m);g.capture.ne=g.yd.createScriptProcessor(b,a,1);g.capture.ne.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.He=n.inputBuffer,za(c,[d]))};g.capture.De.connect(g.capture.ne);g.capture.ne.connect(g.yd.destination);g.capture.stream=
m}var g=h.SDL2;g.capture.Ee=g.yd.createBuffer(a,b,g.yd.sampleRate);g.capture.Ee.getChannelData(0).fill(0);g.capture.xe=setTimeout(function(){g.capture.He=g.capture.Ee;za(c,[d])},b/g.yd.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},61686:(a,b,c,d)=>{var e=h.SDL2;e.audio.ne=e.yd.createScriptProcessor(b,
0,a);e.audio.ne.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Ne=f.outputBuffer,za(c,[d]))};e.audio.ne.connect(e.yd.destination)},62096:(a,b)=>{for(var c=h.SDL2,d=c.capture.He.numberOfChannels,e=0;e<d;++e){var f=c.capture.He.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Aa(a+4*g,f[g]);else for(g=0;g<b;++g)Aa(a+4*(g*d+e),f[g])}},62701:(a,b)=>{for(var c=
h.SDL2,d=c.audio.Ne.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ne.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=y[a+(g*d+e<<2)>>2]}},63181:a=>{var b=h.SDL2;if(a){void 0!==b.capture.xe&&clearTimeout(b.capture.xe);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.ne&&
(b.capture.ne.onaudioprocess=function(){},b.capture.ne.disconnect(),b.capture.ne=void 0);void 0!==b.capture.De&&(b.capture.De.disconnect(),b.capture.De=void 0);void 0!==b.capture.Ee&&(b.capture.Ee=void 0);b.capture=void 0}else void 0!=b.audio.ne&&(b.audio.ne.disconnect(),b.audio.ne=void 0),b.audio=void 0;void 0!==b.yd&&void 0===b.audio&&void 0===b.capture&&(b.yd.close(),b.yd=void 0)},64353:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Ue!==h.canvas&&(d.re=h.createContext(h.canvas,!1,!0),d.Ue=h.canvas);
if(d.w!==a||d.h!==b||d.df!==d.re)d.image=d.re.createImageData(a,b),d.w=a,d.h=b,d.df=d.re;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Xe!==a&&(d.We=new Int32Array(a.buffer),d.Ye=new Uint8Array(a.buffer),d.Xe=a),a=d.We,c=a.length,a.set(u.subarray(b,b+c)),a=d.Ye,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.re.putImageData(d.image,0,0)},65822:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var t=u[e];b[m]=t&255;b[m+1]=t>>8&255;b[m+2]=t>>16&255;b[m+3]=t>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),
n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=A(c.length+1);B(c,d,c.length+1);return d},66811:a=>{h.canvas&&(h.canvas.style.cursor=a?C(r,a):"")},66894:()=>{h.canvas&&(h.canvas.style.cursor="none")},66963:()=>window.innerWidth,66993:()=>window.innerHeight},Ca=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},ya=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>
{b.forEach(d=>{d&&Ca(d,c,()=>{"suspended"===a.state&&a.resume()})})})},za=(a,b)=>{var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)};
function Aa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":fa[a>>0]=b;break;case "i8":fa[a>>0]=b;break;case "i16":ja[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":p("to do setValue(i64) use WASM_BIGINT");case "float":y[a>>2]=b;break;case "double":z[a>>3]=b;break;case "*":x[a>>2]=b;break;default:p(`invalid type for setValue: ${c}`)}}
var Da="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
La=(a,b)=>{Ea=a;Fa=b;if(!D)return 1;Ga||(Ga=!0);if(0==a)E=function(){var d=Math.max(0,Ha+b-Ia())|0;setTimeout(Ja,d)};else if(1==a)E=function(){Ka(Ja)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}E=function(){setImmediate(Ja)}}return 0},Ia;Ia=()=>performance.now();
var Sa=(a,b,c,d,e)=>{!D||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");D=a;Ma=d;var f=F;Ga=!1;Ja=function(){if(!q)if(0<Na.length){var g=Na.shift();g.rf(g.mf);if(Oa){var m=Oa,n=0==m%1?m-1:Math.floor(m);Oa=g.pf?n:(8*m+(n+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",m=Oa,n=Pa.qf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));
f<F||setTimeout(Ja,0)}else f<F||(Qa=Qa+1|0,1==Ea&&1<Fa&&0!=Qa%Fa?E():(0==Ea&&(Ha=Ia()),q||h.preMainLoop&&!1===h.preMainLoop()||(Ra(a),h.postMainLoop&&h.postMainLoop()),f<F||("object"==typeof SDL&&SDL.audio&&SDL.audio.hf&&SDL.audio.hf(),E())))};e||(b&&0<b?La(0,1E3/b):La(1,1),E());if(c)throw"unwind";},Ra=a=>{if(!q)try{a()}catch(b){if("unwind"!=b)throw b;}},Ta=(a,b)=>setTimeout(()=>{Ra(a)},b),Ga=!1,E=null,F=0,D=null,Ma=0,Ea=0,Fa=0,Qa=0,Na=[];
function Ua(){F++;var a=Ea,b=Fa,c=D;D=null;Sa(c,0,!1,Ma,!0);La(a,b);E()}var Pa={},Ha,Ja,Oa,Va=!1,Wa=!1,Xa=[];
function Ya(){function a(){Wa=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Za){Za=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Wa&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function $a(a,b,c,d){if(b&&h.re&&a==h.canvas)return h.re;var e;if(b){var f={antialias:!1,alpha:!1,Pe:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof ab&&(e=bb(a,f)))var m=G[e].te}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof H||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.re=m,b&&cb(e),h.kf=b,Xa.forEach(n=>n()),Ya());return m}var db=!1,eb=void 0,fb=void 0;
function gb(a,b){function c(){Va=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=hb,eb&&d.requestPointerLock(),Va=!0,fb?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=x[SDL.screen>>2]|8388608),ib(h.canvas),jb()):ib(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),fb?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=x[SDL.screen>>2]&
-8388609),ib(h.canvas),jb()):ib(d));if(h.onFullScreen)h.onFullScreen(Va);if(h.onFullscreen)h.onFullscreen(Va)}eb=a;fb=b;"undefined"==typeof eb&&(eb=!0);"undefined"==typeof fb&&(fb=!1);var d=h.canvas;db||(db=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function hb(){if(!Va)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var kb=0;function Ka(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===kb)kb=b+1E3/60;else for(;b+2>=kb;)kb+=1E3/60;setTimeout(a,Math.max(kb-b,0))}}var lb=[];function jb(){var a=h.canvas;lb.forEach(b=>b(a.width,a.height))}
function ib(a,b,c){b&&c?(a.lf=b,a.cf=c):(b=a.lf,c=a.cf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}fb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var mb={},Za,I=12288,nb=!1,ob=0,pb=0,qb=0,J={alpha:!1,depth:!1,stencil:!1,antialias:!1},rb={},ub,vb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},wb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},xb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},yb=1,zb=[],K=[],Ab=[],Bb=[],Cb=[],L=[],Db=[],G=[],M=[],Eb={},Fb=4;function N(a){Gb||(Gb=a)}
var Hb=a=>{for(var b=yb++,c=a.length;c<b;c++)a[c]=null;return b},bb=(a,b)=>{a.Fe||(a.Fe=a.getContext,a.getContext=function(d,e){e=a.Fe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ib(c,b):0},Ib=(a,b)=>{var c=Hb(G),d={handle:c,attributes:b,version:b.Pe,te:a};a.canvas&&(a.canvas.ve=d);G[c]=d;("undefined"==typeof b.$e||b.$e)&&Jb(d);return c},cb=a=>{Kb=G[a];h.re=H=Kb&&Kb.te},Jb=a=>{a||(a=Kb);if(!a.ef){a.ef=!0;var b=a.te;vb(b);wb(b);xb(b);b.se=
b.getExtension("EXT_disjoint_timer_query");b.uf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},ab={},Gb,Kb,Lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+
((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},O=a=>{var b=Lb(a)+1,c=A(b);c&&B(a,c,b);return c},Mb=[],Nb=(a,b)=>{Mb.length=0;for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Mb.push(112==c?x[b>>2]:105==c?u[b>>2]:z[b>>3]);b+=d?8:4}return Mb},Qb=a=>{var b=Ob();a=a();Pb(b);
return a},Rb=0;function Sb(){for(var a=P.length-1;0<=a;--a)Tb(a);P=[];Q=[]}var Q=[];function Ub(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in Q){var f=Q[e];if(f.Je==a&&d(f.Le,c))return}Q.push({Je:a,Re:b,Le:c});Q.sort((g,m)=>g.Re<m.Re)}function Vb(a){for(var b=0;b<Q.length;++b)Q[b].Je==a&&(Q.splice(b,1),--b)}function Wb(){return navigator.userActivation?navigator.userActivation.isActive:Rb&&Xb.we}
function Yb(){if(Wb())for(var a=0;a<Q.length;++a){var b=Q[a];Q.splice(a,1);--a;b.Je.apply(null,b.Le)}}var P=[];function Tb(a){var b=P[a];b.target.removeEventListener(b.me,b.af,b.oe);P.splice(a,1)}function R(a){function b(d){++Rb;Xb=a;Yb();a.qe(d);Yb();--Rb}if(!a.target)return-4;if(a.pe)a.af=b,a.target.addEventListener(a.me,b,a.oe),P.push(a),Zb||(na.push(Sb),Zb=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].me==a.me&&Tb(c--);return 0}
function $b(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function ac(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var bc={},Zb,Xb,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc={},pc=[0,document,window],S=a=>{a=2<a?a?C(r,a):"":a;return pc[a]||document.querySelector(a)},rc=a=>{var b=Lb(a)+1,c=qc(b);B(a,c,b);return c},sc=a=>Qb(()=>{var b=qc(8),c=b+4,d=rc(a.id);if(d=S(d))u[b>>2]=d.width,u[c>>2]=d.height;return[u[b>>2],u[c>>2]]}),tc=(a,b,c)=>{a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},uc=(a,b,c)=>{a.nf?Qb(()=>{var d=rc(a.id);tc(d,b,c)}):(a.width=b,a.height=c)},vc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||
(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),uc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=v,a.style.paddingTop=w,a.style.paddingBottom=ha,a.style.marginLeft=ia,a.style.marginRight=sb,a.style.marginTop=tb,a.style.marginBottom=kd,document.body.style.margin=ld,document.documentElement.style.overflow=
md,document.body.scroll=nd,a.style.ue=od,a.ve&&a.ve.te.viewport(0,0,d,e),oc.ze&&T.apply(null,[oc.ze,37,0,oc.Me]))}var c=sc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,v=a.style.paddingRight,w=a.style.paddingTop,ha=a.style.paddingBottom,ia=a.style.marginLeft,sb=a.style.marginRight,tb=a.style.marginTop,kd=a.style.marginBottom,ld=document.body.style.margin,md=document.documentElement.style.overflow,nd=document.body.scroll,
od=a.style.ue;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},wc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},xc=a=>0>pc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},yc=(a,b)=>{if(0!=b.Ie||0!=b.Ge){vc(a);var c=b.jf?innerWidth:screen.width,d=b.jf?innerHeight:screen.height,e=xc(a),f=e.width;e=e.height;var g=sc(a),m=g[0];g=g[1];3==b.Ie?(wc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ie&&(c*
g<m*d?(f=g*c/m,wc(a,(d-f)/2,0),d=f):(f=m*d/g,wc(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.bf&&(a.style.ue="optimizeSpeed",a.style.ue="-moz-crisp-edges",a.style.ue="-o-crisp-edges",a.style.ue="-webkit-optimize-contrast",a.style.ue="optimize-contrast",a.style.ue="crisp-edges",a.style.ue="pixelated");f=2==b.Ge?devicePixelRatio:1;0!=b.Ge&&
(c=c*f|0,d=d*f|0,uc(a,c,d),a.ve&&a.ve.te.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ac()?-3:-1;oc=b;b.ze&&T.apply(null,[b.ze,37,0,b.Me]);return 0},zc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Ac=(a,b)=>{z[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)z[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)z[a+
8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)u[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];u[a+1296>>2]=b.connected;u[a+1300>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;B(b.id,a+1304,64);B(b.mapping,a+1368,64)},Bc=[],Cc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=H[c](),g=f&&Hb(d);f?(f.name=g,d[g]=f):N(1282);u[b+4*e>>2]=g}},Dc=(a,b,c,d,e,f,g,m)=>{b=K[b];if(a=H[a](b,c))d=m&&B(a.name,m,d),
e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},Ec=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&N(1280);return;case 36345:d=0;break;case 34466:var e=H.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=H.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":N(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:N(1280);
return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:fa[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){N(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:N(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+
e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;x[b>>2]=c;x[b+4>>2]=(c-x[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:fa[b>>0]=d?1:0}}else N(1281)},Fc=(a,b,c)=>{if(c){a=H.se.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d;x[c+4>>2]=(d-x[c>>2])/4294967296}else N(1281)},Gc=(a,b,c)=>{if(c){a=H.se.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else N(1281)},Hc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ic=a=>{var b=
a.ye,c=a.Te,d;if(!b)for(a.ye=b={},a.Se={},d=0;d<H.getProgramParameter(a,35718);++d){var e=H.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Hc(f);g=0<g?f.slice(0,g):f;var m=a.Ke;a.Ke+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Se[m++]=g}},U=a=>{var b=H.Ve;if(b){var c=b.ye[a];"number"==typeof c&&(b.ye[a]=c=H.getUniformLocation(b,b.Se[a]+(0<c?"["+c+"]":"")));return c}N(1282)},Jc=(a,b,c,d)=>{if(c)if(a=K[a],Ic(a),a=H.getUniform(a,U(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;
case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else N(1281)},Kc=(a,b,c,d)=>{if(c)if(a=H.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else N(1281)},Lc=(a,b,c,d,e)=>{a-=
5120;a=1==a?r:4==a?u:6==a?y:5==a||28922==a?x:ka;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Fb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)},V=[],Mc=[],Nc=(a,b)=>{if(!ac())return-1;a=S(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Wb()?yc(a,b):b.Ze?(Ub(yc,1,[a,b]),1):-2:-3:-4},Oc=(a,b)=>{var c={target:S(2),me:"beforeunload",pe:b,qe:(d=event)=>{var e=T.apply(null,[b,28,0,a]);e&&(e=e?C(r,e):"");if(e)return d.preventDefault(),d.returnValue=e},
oe:!0};return R(c)},Pc=(a,b,c,d,e,f)=>{dc||(dc=A(256));a={target:S(a),me:f,pe:d,qe:(g=event)=>{var m=g.target.id?g.target.id:"",n=dc;B($b(g.target),n+0,128);B(m,n+128,128);T.apply(null,[d,e,n,b])&&g.preventDefault()},oe:c};return R(a)},Qc=(a,b,c,d,e)=>{fc||(fc=A(280));return R({target:a,me:e,pe:d,qe:(f=event)=>{var g=fc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;u[g>>2]=n;u[g+4>>2]=ac();var t=n?m:ec,v=t&&t.id?t.id:
"";B($b(t),g+8,128);B(v,g+136,128);u[g+264>>2]=t?t.clientWidth:0;u[g+268>>2]=t?t.clientHeight:0;u[g+272>>2]=screen.width;u[g+276>>2]=screen.height;n&&(ec=m);T.apply(null,[d,19,g,b])&&f.preventDefault()},oe:c})},Rc=(a,b,c,d,e)=>{gc||(gc=A(1432));b={target:S(2),we:!0,me:e,pe:c,qe:(f=event)=>{var g=gc;Ac(g,f.gamepad);T.apply(null,[c,d,g,a])&&f.preventDefault()},oe:b};return R(b)},Sc=(a,b,c,d,e,f)=>{hc||(hc=A(176));a={target:S(a),we:!0,me:f,pe:d,qe:g=>{var m=hc;z[m>>3]=g.timeStamp;var n=m>>2;u[n+2]=g.location;
u[n+3]=g.ctrlKey;u[n+4]=g.shiftKey;u[n+5]=g.altKey;u[n+6]=g.metaKey;u[n+7]=g.repeat;u[n+8]=g.charCode;u[n+9]=g.keyCode;u[n+10]=g.which;B(g.key||"",m+44,32);B(g.code||"",m+76,32);B(g.char||"",m+108,32);B(g.locale||"",m+140,32);T.apply(null,[d,e,m,b])&&g.preventDefault()},oe:c};return R(a)},Tc=(a,b,c)=>{z[a>>3]=b.timeStamp;a>>=2;u[a+2]=b.screenX;u[a+3]=b.screenY;u[a+4]=b.clientX;u[a+5]=b.clientY;u[a+6]=b.ctrlKey;u[a+7]=b.shiftKey;u[a+8]=b.altKey;u[a+9]=b.metaKey;ja[2*a+20]=b.button;ja[2*a+21]=b.buttons;
u[a+11]=b.movementX;u[a+12]=b.movementY;c=xc(c);u[a+13]=b.clientX-c.left;u[a+14]=b.clientY-c.top},Uc=(a,b,c,d,e,f)=>{ic||(ic=A(72));a=S(a);return R({target:a,we:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,me:f,pe:d,qe:(g=event)=>{Tc(ic,g,a);T.apply(null,[d,e,ic,b])&&g.preventDefault()},oe:c})},Vc=(a,b,c,d,e)=>{jc||(jc=A(260));return R({target:a,me:e,pe:d,qe:(f=event)=>{var g=jc,m=document.pointerLockElement||document.Fe||document.gf||document.ff;u[g>>2]=!!m;var n=m&&m.id?m.id:"";B($b(m),g+4,
128);B(n,g+132,128);T.apply(null,[d,20,g,b])&&f.preventDefault()},oe:c})},Wc=(a,b,c,d)=>{kc||(kc=A(36));a=S(a);return R({target:a,me:"resize",pe:d,qe:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=kc;u[g>>2]=e.detail;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset;u[g+32>>2]=pageYOffset;T.apply(null,[d,10,g,b])&&e.preventDefault()}}},oe:c})},Xc=(a,b,c,d,e,f)=>{lc||(lc=A(1696));
a=S(a);return R({target:a,we:"touchstart"==f||"touchend"==f,me:f,pe:d,qe:g=>{for(var m,n={},t=g.touches,v=0;v<t.length;++v)m=t[v],m.Oe=m.Qe=0,n[m.identifier]=m;for(v=0;v<g.changedTouches.length;++v)m=g.changedTouches[v],m.Oe=1,n[m.identifier]=m;for(v=0;v<g.targetTouches.length;++v)n[g.targetTouches[v].identifier].Qe=1;t=lc;z[t>>3]=g.timeStamp;var w=t>>2;u[w+3]=g.ctrlKey;u[w+4]=g.shiftKey;u[w+5]=g.altKey;u[w+6]=g.metaKey;w+=7;var ha=xc(a),ia=0;for(v in n)if(m=n[v],u[w]=m.identifier,u[w+1]=m.screenX,
u[w+2]=m.screenY,u[w+3]=m.clientX,u[w+4]=m.clientY,u[w+5]=m.pageX,u[w+6]=m.pageY,u[w+7]=m.Oe,u[w+8]=m.Qe,u[w+9]=m.clientX-ha.left,u[w+10]=m.clientY-ha.top,w+=13,31<++ia)break;u[t+8>>2]=ia;T.apply(null,[d,e,t,b])&&g.preventDefault()},oe:c})},Yc=(a,b,c)=>{var d=pc[1];mc||(mc=A(8));return R({target:d,me:"visibilitychange",pe:c,qe:(e=event)=>{var f=mc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);u[f>>2]=document.hidden;u[f+4>>2]=g;T.apply(null,[c,21,f,a])&&e.preventDefault()},
oe:b})},Zc=(a,b,c,d)=>{nc||(nc=A(104));return R({target:a,we:!0,me:"wheel",pe:d,qe:(e=event)=>{var f=nc;Tc(f,e,a);z[f+72>>3]=e.deltaX;z[f+80>>3]=e.deltaY;z[f+88>>3]=e.deltaZ;u[f+96>>2]=e.deltaMode;T.apply(null,[d,9,f,b])&&e.preventDefault()},oe:c})},$c={},bd=()=>{if(!ad){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in $c)void 0===
$c[b]?delete a[b]:a[b]=$c[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ad=c}return ad},ad,cd=[null,[],[]],dd=a=>{try{a()}catch(b){p(b)}};function ed(){var a=W,b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"==typeof e?function(){fd.push(d);try{return e.apply(null,arguments)}finally{q||(fd.pop()===d||p(),X&&1===Y&&0===fd.length&&(Y=0,dd(gd),"undefined"!=typeof Fibers&&Fibers.vf()))}}:e})(c);return b}var Y=0,X=null,hd=0,fd=[],jd={},pd={},qd=0,rd=null,sd=[];
function td(){var a=A(4108),b=a+12;x[a>>2]=b;x[a+4>>2]=b+4096;b=fd[0];var c=jd[b];void 0===c&&(c=qd++,jd[b]=c,pd[c]=b);u[a+8>>2]=c;return a}
function ud(a){if(!q){if(0===Y){var b=!1,c=!1;a((d=0)=>{if(!q&&(hd=d,b=!0,c)){Y=2;dd(()=>vd(X));"undefined"!=typeof mb&&D&&Ua();d=!1;try{var e=(0,W[pd[u[X+8>>2]]])()}catch(m){e=m,d=!0}var f=!1;if(!X){var g=rd;g&&(rd=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Y=1,X=td(),"undefined"!=typeof mb&&D&&(E=null,F++),dd(()=>wd(X)))}else 2===Y?(Y=0,dd(xd),yd(X),X=null,sd.forEach(d=>Ra(d))):p(`invalid state: ${Y}`);return hd}}h.requestFullscreen=(a,b)=>gb(a,b);
h.requestAnimationFrame=a=>Ka(a);h.setCanvasSize=(a,b,c)=>{ib(h.canvas,a,b);c||jb()};h.pauseMainLoop=()=>{E=null;F++};h.resumeMainLoop=()=>Ua();h.getUserMedia=()=>{window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=(a,b,c,d)=>$a(a,b,c,d);for(var H,Z=0;32>Z;++Z)Bc.push(Array(Z));var zd=new Float32Array(288);for(Z=0;288>Z;++Z)V[Z]=zd.subarray(0,Z+1);var Ad=new Int32Array(288);
for(Z=0;288>Z;++Z)Mc[Z]=Ad.subarray(0,Z+1);
var Bd={H:function(){return 0},Sa:function(){return 0},Ta:function(){},Ua:()=>!0,f:()=>{p("")},Ga:a=>{if(12448==a)return I=12288,1;I=12300;return 0},ic:(a,b,c,d,e)=>{if(62E3!=a)I=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)J.alpha=0<u[b+4>>2];else if(12325==a)J.depth=0<u[b+4>>2];else if(12326==a)J.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],J.antialias=0<a;else if(12338==a)a=u[b+4>>2],J.antialias=1==a;else if(12544==a)J.sf=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>
2]=1),c&&0<d&&(x[c>>2]=62002),I=12288,c=1):(I=12300,c=0)}return c},Ob:(a,b,c,d)=>{if(62E3!=a)return I=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return I=12292,0;d+=8}if(2!=a)return I=12293,0;J.Pe=a-1;J.tf=0;ub=bb(h.canvas,J);if(0!=ub)return I=12288,cb(ub),h.kf=!0,Xa.forEach(function(e){e()}),cb(null),62004;I=12297;return 0},rb:(a,b)=>{if(62E3!=a)return I=12296,0;if(62002!=b)return I=12293,0;I=12288;return 62006},Db:(a,b)=>{if(62E3!=a)return I=12296,0;if(62004!=
b)return I=12294,0;a=ub;Kb===G[a]&&(Kb=null);if("object"==typeof bc)for(var c=G[a].te.canvas,d=0;d<P.length;++d)P[d].target!=c||Tb(d--);G[a]&&G[a].te.canvas&&(G[a].te.canvas.ve=void 0);G[a]=null;I=12288;ob==b&&(ob=0);return 1},gb:(a,b)=>{if(62E3!=a)return I=12296,0;if(62006!=b)return I=12301,1;pb==b&&(pb=0);qb==b&&(qb=0);I=12288;return 1},Zb:(a,b,c,d)=>{if(62E3!=a)return I=12296,0;if(62002!=b)return I=12293,0;if(!d)return I=12300,0;I=12288;switch(c){case 12320:return u[d>>2]=J.alpha?32:24,1;case 12321:return u[d>>
2]=J.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=J.depth?24:0,1;case 12326:return u[d>>2]=J.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>
2]=J.antialias?4:0,1;case 12338:return u[d>>2]=J.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return I=12292,0}},I:()=>{I=12288;return 62E3},Ea:()=>I,Ec:(a,b,c)=>{if(62E3!=
a)return I=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);nb=!0;I=12288;return 1},Xa:(a,b,c,d)=>{if(62E3!=a)return I=12296,0;if(0!=d&&62004!=d)return I=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return I=12301,0;cb(d?ub:null);ob=d;qb=b;pb=c;I=12288;return 1},Fa:(a,b)=>{if(62E3!=a)return I=12296,0;I=12288;if(rb[b])return rb[b];switch(b){case 12371:a=O("Emscripten");break;case 12372:a=O("1.4 Emscripten EGL");break;case 12373:a=O("");break;case 12429:a=O("OpenGL_ES");break;default:return I=12300,0}return rb[b]=
a},Pa:()=>{if(nb)if(h.re)if(h.re.isContextLost())I=12302;else return I=12288,1;else I=12290;else I=12289;return 0},Ja:(a,b)=>{if(62E3!=a)return I=12296,0;0==b?La(0,0):La(1,b);I=12288;return 1},tc:a=>{if(62E3!=a)return I=12296,0;qb=pb=ob=0;nb=!1;I=12288;return 1},Ha:()=>{I=12288;return 1},Ia:()=>{I=12288;return 1},Ba:(a,b,c)=>{b=Nb(b,c);return Ba[a].apply(null,b)},a:(a,b,c)=>{b=Nb(b,c);return Ba[a].apply(null,b)},sb:()=>{E=null;F++;D=null},Va:()=>Date.now(),ya:()=>{if(!ac())return-1;Vb(yc);var a=pc[1];
if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ca:()=>{Vb(zc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},d:()=>devicePixelRatio,b:(a,b,c)=>{a=S(a);if(!a)return-4;a=xc(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},ba:(a,b)=>{if(0>a||a>=cc.length)return-5;if(!cc[a])return-7;Ac(b,cc[a]);return 0},i:Ia,ma:()=>cc.length,Da:(a,b)=>{u[a>>2]=screen.width;
u[b>>2]=screen.height},ca:function(a){H.activeTexture(a)},aa:(a,b)=>{H.attachShader(K[a],L[b])},ta:(a,b)=>{H.se.beginQueryEXT(a,M[b])},$:(a,b,c)=>{H.bindAttribLocation(K[a],b,c?C(r,c):"")},_:(a,b)=>{H.bindBuffer(a,zb[b])},Z:(a,b)=>{H.bindFramebuffer(a,Ab[b])},Y:(a,b)=>{H.bindRenderbuffer(a,Bb[b])},X:(a,b)=>{H.bindTexture(a,Cb[b])},ka:a=>{H.bindVertexArray(Db[a])},W:function(a,b,c,d){H.blendColor(a,b,c,d)},V:function(a){H.blendEquation(a)},U:function(a,b){H.blendEquationSeparate(a,b)},T:function(a,
b){H.blendFunc(a,b)},S:function(a,b,c,d){H.blendFuncSeparate(a,b,c,d)},R:(a,b,c,d)=>{H.bufferData(a,c?r.subarray(c,c+b):b,d)},Q:(a,b,c,d)=>{H.bufferSubData(a,b,r.subarray(d,d+c))},P:function(a){return H.checkFramebufferStatus(a)},O:function(a){H.clear(a)},N:function(a,b,c,d){H.clearColor(a,b,c,d)},M:function(a){H.clearDepth(a)},L:function(a){H.clearStencil(a)},K:(a,b,c,d)=>{H.colorMask(!!a,!!b,!!c,!!d)},J:a=>{H.compileShader(L[a])},qd:(a,b,c,d,e,f,g,m)=>{H.compressedTexImage2D(a,b,c,d,e,f,m?r.subarray(m,
m+g):null)},pd:(a,b,c,d,e,f,g,m,n)=>{H.compressedTexSubImage2D(a,b,c,d,e,f,g,n?r.subarray(n,n+m):null)},od:function(a,b,c,d,e,f,g,m){H.copyTexImage2D(a,b,c,d,e,f,g,m)},nd:function(a,b,c,d,e,f,g,m){H.copyTexSubImage2D(a,b,c,d,e,f,g,m)},md:()=>{var a=Hb(K),b=H.createProgram();b.name=a;b.Ce=b.Ae=b.Be=0;b.Ke=1;K[a]=b;return a},ld:a=>{var b=Hb(L);L[b]=H.createShader(a);return b},kd:function(a){H.cullFace(a)},jd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=zb[d];e&&(H.deleteBuffer(e),e.name=0,zb[d]=
null)}},id:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Ab[d];e&&(H.deleteFramebuffer(e),e.name=0,Ab[d]=null)}},hd:a=>{if(a){var b=K[a];b?(H.deleteProgram(b),b.name=0,K[a]=null):N(1281)}},va:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=M[d];e&&(H.se.deleteQueryEXT(e),M[d]=null)}},gd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Bb[d];e&&(H.deleteRenderbuffer(e),e.name=0,Bb[d]=null)}},fd:a=>{if(a){var b=L[a];b?(H.deleteShader(b),L[a]=null):N(1281)}},ed:(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=Cb[d];e&&(H.deleteTexture(e),e.name=0,Cb[d]=null)}},ja:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];H.deleteVertexArray(Db[d]);Db[d]=null}},dd:function(a){H.depthFunc(a)},cd:a=>{H.depthMask(!!a)},bd:function(a,b){H.depthRange(a,b)},ad:(a,b)=>{H.detachShader(K[a],L[b])},$c:function(a){H.disable(a)},_c:a=>{H.disableVertexAttribArray(a)},Zc:(a,b,c)=>{H.drawArrays(a,b,c)},fa:(a,b,c,d)=>{H.drawArraysInstanced(a,b,c,d)},ga:(a,b)=>{for(var c=Bc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];H.drawBuffers(c)},
Yc:(a,b,c,d)=>{H.drawElements(a,b,c,d)},ea:(a,b,c,d,e)=>{H.drawElementsInstanced(a,b,c,d,e)},Xc:function(a){H.enable(a)},Wc:a=>{H.enableVertexAttribArray(a)},sa:a=>{H.se.endQueryEXT(a)},Vc:function(){H.finish()},Uc:function(){H.flush()},Tc:(a,b,c,d)=>{H.framebufferRenderbuffer(a,b,c,Bb[d])},Sc:(a,b,c,d,e)=>{H.framebufferTexture2D(a,b,c,Cb[d],e)},Rc:function(a){H.frontFace(a)},Qc:(a,b)=>{Cc(a,b,"createBuffer",zb)},Oc:(a,b)=>{Cc(a,b,"createFramebuffer",Ab)},wa:(a,b)=>{for(var c=0;c<a;c++){var d=H.se.createQueryEXT();
if(!d){for(N(1282);c<a;)u[b+4*c++>>2]=0;break}var e=Hb(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},Nc:(a,b)=>{Cc(a,b,"createRenderbuffer",Bb)},Mc:(a,b)=>{Cc(a,b,"createTexture",Cb)},ia:function(a,b){Cc(a,b,"createVertexArray",Db)},Pc:function(a){H.generateMipmap(a)},Lc:(a,b,c,d,e,f,g)=>{Dc("getActiveAttrib",a,b,c,d,e,f,g)},Kc:(a,b,c,d,e,f,g)=>{Dc("getActiveUniform",a,b,c,d,e,f,g)},Jc:(a,b,c,d)=>{a=H.getAttachedShaders(K[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=L.indexOf(a[b])},Ic:(a,
b)=>H.getAttribLocation(K[a],b?C(r,b):""),Hc:(a,b)=>{Ec(a,b,4)},Gc:(a,b,c)=>{c?u[c>>2]=H.getBufferParameter(a,b):N(1281)},Fc:()=>{var a=H.getError()||Gb;Gb=0;return a},Dc:(a,b)=>{Ec(a,b,2)},Cc:(a,b,c,d)=>{a=H.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Bc:(a,b)=>{Ec(a,b,0)},zc:(a,b,c,d)=>{a=H.getProgramInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(u[c>>2]=b)},Ac:(a,b,c)=>{if(c)if(a>=yb)N(1281);
else if(a=K[a],35716==b)a=H.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Ce)for(b=0;b<H.getProgramParameter(a,35718);++b)a.Ce=Math.max(a.Ce,H.getActiveUniform(a,b).name.length+1);u[c>>2]=a.Ce}else if(35722==b){if(!a.Ae)for(b=0;b<H.getProgramParameter(a,35721);++b)a.Ae=Math.max(a.Ae,H.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Ae}else if(35381==b){if(!a.Be)for(b=0;b<H.getProgramParameter(a,35382);++b)a.Be=Math.max(a.Be,H.getActiveUniformBlockName(a,
b).length+1);u[c>>2]=a.Be}else u[c>>2]=H.getProgramParameter(a,b);else N(1281)},na:Fc,pa:Gc,la:Fc,oa:Gc,qa:(a,b,c)=>{c?u[c>>2]=H.se.getQueryEXT(a,b):N(1281)},yc:(a,b,c)=>{c?u[c>>2]=H.getRenderbufferParameter(a,b):N(1281)},wc:(a,b,c,d)=>{a=H.getShaderInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(u[c>>2]=b)},vc:(a,b,c,d)=>{a=H.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},uc:(a,b,c,d)=>{if(a=H.getShaderSource(L[a]))b=0<b&&d?B(a,d,
b):0,c&&(u[c>>2]=b)},xc:(a,b,c)=>{c?35716==b?(a=H.getShaderInfoLog(L[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=H.getShaderSource(L[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=H.getShaderParameter(L[a],b):N(1281)},sc:a=>{var b=Eb[a];if(!b){switch(a){case 7939:b=H.getSupportedExtensions()||[];b=b.concat(b.map(d=>"GL_"+d));b=O(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=H.getParameter(a))||N(1280);b=b&&O(b);break;case 7938:b=O("OpenGL ES 2.0 ("+H.getParameter(7938)+
")");break;case 35724:b=H.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=O(b);break;default:N(1280)}Eb[a]=b}return b},rc:(a,b,c)=>{c?y[c>>2]=H.getTexParameter(a,b):N(1281)},qc:(a,b,c)=>{c?u[c>>2]=H.getTexParameter(a,b):N(1281)},nc:(a,b)=>{b=b?C(r,b):"";if(a=K[a]){Ic(a);var c=a.ye,d=0,e=b,f=Hc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Te[e])&&d<e[0]&&(d+=e[1],c[d]=
c[d]||H.getUniformLocation(a,b)))return d}else N(1281);return-1},pc:(a,b,c)=>{Jc(a,b,c,2)},oc:(a,b,c)=>{Jc(a,b,c,0)},kc:(a,b,c)=>{c?u[c>>2]=H.getVertexAttribOffset(a,b):N(1281)},mc:(a,b,c)=>{Kc(a,b,c,2)},lc:(a,b,c)=>{Kc(a,b,c,5)},jc:function(a,b){H.hint(a,b)},hc:a=>(a=zb[a])?H.isBuffer(a):0,gc:function(a){return H.isEnabled(a)},fc:a=>(a=Ab[a])?H.isFramebuffer(a):0,ec:a=>(a=K[a])?H.isProgram(a):0,ua:a=>(a=M[a])?H.se.isQueryEXT(a):0,dc:a=>(a=Bb[a])?H.isRenderbuffer(a):0,cc:a=>(a=L[a])?H.isShader(a):
0,bc:a=>(a=Cb[a])?H.isTexture(a):0,ha:a=>(a=Db[a])?H.isVertexArray(a):0,ac:function(a){H.lineWidth(a)},$b:a=>{a=K[a];H.linkProgram(a);a.ye=0;a.Te={}},_b:(a,b)=>{3317==a&&(Fb=b);H.pixelStorei(a,b)},Yb:function(a,b){H.polygonOffset(a,b)},ra:(a,b)=>{H.se.queryCounterEXT(M[a],b)},Xb:(a,b,c,d,e,f,g)=>{(g=Lc(f,e,c,d,g))?H.readPixels(a,b,c,d,e,f,g):N(1280)},Wb:()=>{},Vb:function(a,b,c,d){H.renderbufferStorage(a,b,c,d)},Ub:(a,b)=>{H.sampleCoverage(a,!!b)},Tb:function(a,b,c,d){H.scissor(a,b,c,d)},Sb:()=>{N(1280)},
Rb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=d?u[d+4*f>>2]:-1,m=u[c+4*f>>2];g=m?C(r,m,0>g?void 0:g):"";e+=g}H.shaderSource(L[a],e)},Qb:function(a,b,c){H.stencilFunc(a,b,c)},Pb:function(a,b,c,d){H.stencilFuncSeparate(a,b,c,d)},Nb:function(a){H.stencilMask(a)},Mb:function(a,b){H.stencilMaskSeparate(a,b)},Lb:function(a,b,c){H.stencilOp(a,b,c)},Kb:function(a,b,c,d){H.stencilOpSeparate(a,b,c,d)},Jb:(a,b,c,d,e,f,g,m,n)=>{H.texImage2D(a,b,c,d,e,f,g,m,n?Lc(m,g,d,e,n):null)},Ib:function(a,b,c){H.texParameterf(a,
b,c)},Hb:(a,b,c)=>{H.texParameterf(a,b,y[c>>2])},Gb:function(a,b,c){H.texParameteri(a,b,c)},Fb:(a,b,c)=>{H.texParameteri(a,b,u[c>>2])},Eb:(a,b,c,d,e,f,g,m,n)=>{var t=null;n&&(t=Lc(m,g,e,f,n));H.texSubImage2D(a,b,c,d,e,f,g,m,t)},Cb:(a,b)=>{H.uniform1f(U(a),b)},Bb:(a,b,c)=>{if(288>=b)for(var d=V[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);H.uniform1fv(U(a),d)},Ab:(a,b)=>{H.uniform1i(U(a),b)},zb:(a,b,c)=>{if(288>=b)for(var d=Mc[b-1],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>
2,c+4*b>>2);H.uniform1iv(U(a),d)},yb:(a,b,c)=>{H.uniform2f(U(a),b,c)},xb:(a,b,c)=>{if(144>=b)for(var d=V[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);H.uniform2fv(U(a),d)},wb:(a,b,c)=>{H.uniform2i(U(a),b,c)},vb:(a,b,c)=>{if(144>=b)for(var d=Mc[2*b-1],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);H.uniform2iv(U(a),d)},ub:(a,b,c,d)=>{H.uniform3f(U(a),b,c,d)},tb:(a,b,c)=>{if(96>=b)for(var d=V[3*b-1],e=0;e<3*b;e+=
3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);H.uniform3fv(U(a),d)},qb:(a,b,c,d)=>{H.uniform3i(U(a),b,c,d)},pb:(a,b,c)=>{if(96>=b)for(var d=Mc[3*b-1],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2];else d=u.subarray(c>>2,c+12*b>>2);H.uniform3iv(U(a),d)},ob:(a,b,c,d,e)=>{H.uniform4f(U(a),b,c,d,e)},nb:(a,b,c)=>{if(72>=b){var d=V[4*b-1],e=y;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];
d[f+3]=e[g+3]}}else d=y.subarray(c>>2,c+16*b>>2);H.uniform4fv(U(a),d)},mb:(a,b,c,d,e)=>{H.uniform4i(U(a),b,c,d,e)},lb:(a,b,c)=>{if(72>=b)for(var d=Mc[4*b-1],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);H.uniform4iv(U(a),d)},kb:(a,b,c,d)=>{if(72>=b)for(var e=V[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);H.uniformMatrix2fv(U(a),
!!c,e)},jb:(a,b,c,d)=>{if(32>=b)for(var e=V[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);H.uniformMatrix3fv(U(a),!!c,e)},ib:(a,b,c,d)=>{if(18>=b){var e=V[16*b-1],f=y;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+
5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=y.subarray(d>>2,d+64*b>>2);H.uniformMatrix4fv(U(a),!!c,e)},hb:a=>{a=K[a];H.useProgram(a);H.Ve=a},fb:a=>{H.validateProgram(K[a])},eb:function(a,b){H.vertexAttrib1f(a,b)},db:(a,b)=>{H.vertexAttrib1f(a,y[b>>2])},cb:function(a,b,c){H.vertexAttrib2f(a,b,c)},bb:(a,b)=>{H.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},ab:function(a,b,c,d){H.vertexAttrib3f(a,
b,c,d)},$a:(a,b)=>{H.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},_a:function(a,b,c,d,e){H.vertexAttrib4f(a,b,c,d,e)},Za:(a,b)=>{H.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},da:(a,b)=>{H.vertexAttribDivisor(a,b)},Ya:(a,b,c,d,e,f)=>{H.vertexAttribPointer(a,b,c,!!d,e,f)},Wa:function(a,b,c,d){H.viewport(a,b,c,d)},k:()=>1,Oa:(a,b,c)=>r.copyWithin(a,b,b+c),za:(a,b,c)=>Nc(a,{Ie:u[c>>2],Ge:u[c+4>>2],bf:u[c+8>>2],Ze:b,ze:u[c+12>>2],Me:u[c+16>>2]}),F:(a,b)=>{a=S(a);return a?a.requestPointerLock?
Wb()?zc(a):b?(Ub(zc,2,[a]),1):-2:-1:-4},La:()=>{p("OOM")},xa:()=>(cc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1,l:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Oc(a,b),x:(a,b,c,d)=>Pc(a,b,c,d,12,"blur"),c:tc,h:(a,b,c)=>{a=S(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},y:(a,b,c,d)=>Pc(a,b,c,d,13,"focus"),o:(a,b,c,d)=>{if(!ac())return-1;a=S(a);if(!a)return-4;Qc(a,b,c,d,"webkitfullscreenchange");
return Qc(a,b,c,d,"fullscreenchange")},e:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?Rc(a,b,c,26,"gamepadconnected"):-1,g:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?Rc(a,b,c,27,"gamepaddisconnected"):-1,r:(a,b,c,d)=>Sc(a,b,c,d,2,"keydown"),p:(a,b,c,d)=>Sc(a,b,c,d,1,"keypress"),q:(a,b,c,d)=>Sc(a,b,c,d,3,"keyup"),sd:(a,b,c)=>{Sa(()=>dynCall_v.call(null,a),b,c)},rd:La,D:(a,b,c,d)=>Uc(a,b,c,d,5,"mousedown"),B:(a,b,c,d)=>Uc(a,b,c,d,33,"mouseenter"),A:(a,b,c,d)=>Uc(a,b,
c,d,34,"mouseleave"),E:(a,b,c,d)=>Uc(a,b,c,d,8,"mousemove"),C:(a,b,c,d)=>Uc(a,b,c,d,6,"mouseup"),s:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Fe||document.body.gf||document.body.ff))return-1;a=S(a);if(!a)return-4;Vc(a,b,c,d,"mozpointerlockchange");Vc(a,b,c,d,"webkitpointerlockchange");Vc(a,b,c,d,"mspointerlockchange");return Vc(a,b,c,d,"pointerlockchange")},n:(a,b,c,d)=>Wc(a,b,c,d),t:(a,b,c,d)=>Xc(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>Xc(a,b,c,d,23,
"touchend"),u:(a,b,c,d)=>Xc(a,b,c,d,24,"touchmove"),w:(a,b,c,d)=>Xc(a,b,c,d,22,"touchstart"),m:(a,b,c)=>Yc(a,b,c),z:(a,b,c,d)=>(a=S(a))?"undefined"!=typeof a.onwheel?Zc(a,b,c,d):-1:-4,Aa:a=>document.title=a?C(r,a):"",j:a=>ud(b=>Ta(b,a)),Ma:(a,b)=>{var c=0;bd().forEach((d,e)=>{var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)fa[e++>>0]=d.charCodeAt(f);fa[e>>0]=0;c+=d.length+1});return 0},Na:(a,b)=>{var c=bd();x[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);x[b>>2]=d;return 0},G:()=>52,Ra:()=>
52,Ka:function(){return 70},Qa:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=x[b>>2],m=x[b+4>>2];b+=8;for(var n=0;n<m;n++){var t=r[g+n],v=cd[a];0===t||10===t?((1===a?da:l)(C(v,0)),v.length=0):v.push(t)}e+=m}x[d>>2]=e;return 0}},W=function(){var a={a:Bd};pa++;xa(a,function(b){W=b.instance.exports;W=ed();ea=W.td;b=ea.buffer;h.HEAP8=fa=new Int8Array(b);h.HEAP16=ja=new Int16Array(b);h.HEAPU8=r=new Uint8Array(b);h.HEAPU16=ka=new Uint16Array(b);h.HEAP32=u=new Int32Array(b);h.HEAPU32=x=new Uint32Array(b);h.HEAPF32=
y=new Float32Array(b);h.HEAPF64=z=new Float64Array(b);ma.unshift(W.ud);pa--;0==pa&&(null!==qa&&(clearInterval(qa),qa=null),ra&&(b=ra,ra=null,b()))}).catch(ba);return{}}();h._playTromino=(a,b,c,d)=>(h._playTromino=W.vd)(a,b,c,d);
var yd=a=>(yd=W.wd)(a),A=a=>(A=W.xd)(a),Ob=()=>(Ob=W.zd)(),Pb=a=>(Pb=W.Ad)(a),qc=a=>(qc=W.Bd)(a),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=W.Cd)(a,b),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=W.Dd)(a,b,c),dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=W.Ed)(a);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=W.Fd)(a,b,c,d,e);h.dynCall_ii=(a,b)=>(h.dynCall_ii=W.Gd)(a,b);var T=h.dynCall_iiii=(a,b,c,d)=>(T=h.dynCall_iiii=W.Hd)(a,b,c,d);
h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=W.Id)(a,b,c,d);var dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=W.Jd)(a,b,c);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=W.Kd)(a,b,c,d,e,f);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_iiiiiiii=W.Ld)(a,b,c,d,e,f,g,m);h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,m,n,t)=>(h.dynCall_iiiiiiiiii=W.Md)(a,b,c,d,e,f,g,m,n,t);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=W.Nd)(a,b,c,d,e);
h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,m,n,t,v,w,ha,ia,sb,tb)=>(h.dynCall_iiiiiiiiiiiiiiff=W.Od)(a,b,c,d,e,f,g,m,n,t,v,w,ha,ia,sb,tb);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=W.Pd)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=W.Qd)(a,b);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=W.Rd)(a,b,c,d,e,f);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_iiiiiiiii=W.Sd)(a,b,c,d,e,f,g,m,n);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_viiiiiii=W.Td)(a,b,c,d,e,f,g,m);
h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,m,n,t,v,w)=>(h.dynCall_viiiiiiiiiii=W.Ud)(a,b,c,d,e,f,g,m,n,t,v,w);h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,m,n,t,v)=>(h.dynCall_iiiiiidiiff=W.Vd)(a,b,c,d,e,f,g,m,n,t,v);h.dynCall_i=a=>(h.dynCall_i=W.Wd)(a);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=W.Xd)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=W.Yd)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_viiiiiiii=W.Zd)(a,b,c,d,e,f,g,m,n);
h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,m,n,t)=>(h.dynCall_viiiiiiiii=W._d)(a,b,c,d,e,f,g,m,n,t);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=W.$d)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=W.ae)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=W.be)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=W.ce)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=W.de)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=W.ee)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=W.fe)(a,b,c,d,e,f);
h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=W.ge)(a,b,c,d,e,f,g);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=W.he)(a,b,c,d,e,f,g);var wd=a=>(wd=W.ie)(a),gd=()=>(gd=W.je)(),vd=a=>(vd=W.ke)(a),xd=()=>(xd=W.le)(),Cd;ra=function Dd(){Cd||Ed();Cd||(ra=Dd)};function Ed(){if(!(0<pa)){for(;0<la.length;)la.shift()(h);if(!(0<pa||Cd||(Cd=!0,h.calledRun=!0,q))){for(;0<ma.length;)ma.shift()(h);for(aa(h);0<oa.length;)oa.shift()(h)}}}Ed();


  return moduleArg.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createTrmnMod;
else if (typeof define === 'function' && define['amd'])
  define([], () => createTrmnMod);
