
var createTrmnMod = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(createTrmnMod) {
  createTrmnMod = createTrmnMod || {};


null;var f;f||(f=typeof createTrmnMod !== 'undefined' ? createTrmnMod : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},f),da="./this.program",ea=(a,b)=>{throw b;},k="",fa;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);_scriptDir&&(k=_scriptDir);0!==k.indexOf("blob:")?k=k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):k="";fa=a=>{document.title=a};var ha=f.print||console.log.bind(console),l=f.printErr||console.warn.bind(console);
Object.assign(f,ca);ca=null;f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);var ia;f.wasmBinary&&(ia=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");var ja,q=!1,ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ka)return ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function t(a,b){return a?la(w,a,b):""}
function ma(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function x(a,b,c){return ma(a,w,b,c)}
function na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var y,w,oa,pa,z,A,B,C,ra=[],sa=[],ta=[],ua=[];function va(){var a=f.preRun.shift();ra.unshift(a)}var wa=0,xa=null,ya=null;function p(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";l(a);q=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
function za(){return D.startsWith("data:application/octet-stream;base64,")}var D;D="trmn-wasm.wasm";if(!za()){var Aa=D;D=f.locateFile?f.locateFile(Aa,k):k+Aa}function Ba(){var a=D;try{if(a==D&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function Ca(){return ia||"function"!=typeof fetch?Promise.resolve().then(function(){return Ba()}):fetch(D,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+D+"'";return a.arrayBuffer()}).catch(function(){return Ba()})}
var Da,Ea,Ia={58152:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,58299:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,58533:a=>{"undefined"===typeof f.SDL2&&(f.SDL2={});var b=f.SDL2;a?b.capture={}:b.audio={};b.zd||("undefined"!==typeof AudioContext?b.zd=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.zd=new webkitAudioContext),b.zd&&
Fa(b.zd));return void 0===b.zd?-1:0},59026:()=>f.SDL2.zd.sampleRate,59094:(a,b,c,d)=>{function e(){}function g(m){void 0!==h.capture.ye&&(clearTimeout(h.capture.ye),h.capture.ye=void 0);h.capture.Fe=h.zd.createMediaStreamSource(m);h.capture.oe=h.zd.createScriptProcessor(b,a,1);h.capture.oe.onaudioprocess=function(n){void 0!==h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.Je=n.inputBuffer,Ga(c,[d]))};h.capture.Fe.connect(h.capture.oe);h.capture.oe.connect(h.zd.destination);
h.capture.stream=m}var h=f.SDL2;h.capture.He=h.zd.createBuffer(a,b,h.zd.sampleRate);h.capture.He.getChannelData(0).fill(0);h.capture.ye=setTimeout(function(){h.capture.Je=h.capture.He;Ga(c,[d])},b/h.zd.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},60746:(a,b,c,d)=>{var e=f.SDL2;e.audio.oe=
e.zd.createScriptProcessor(b,0,a);e.audio.oe.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(e.audio.Pe=g.outputBuffer,Ga(c,[d]))};e.audio.oe.connect(e.zd.destination)},61156:(a,b)=>{for(var c=f.SDL2,d=c.capture.Je.numberOfChannels,e=0;e<d;++e){var g=c.capture.Je.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)Ha(a+4*h,g[h]);else for(h=0;h<b;++h)Ha(a+4*(h*d+e),
g[h])}},61761:(a,b)=>{for(var c=f.SDL2,d=c.audio.Pe.numberOfChannels,e=0;e<d;++e){var g=c.audio.Pe.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)g[h]=B[a+(h*d+e<<2)>>2]}},62241:a=>{var b=f.SDL2;if(a){void 0!==b.capture.ye&&clearTimeout(b.capture.ye);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=
void 0}void 0!==b.capture.oe&&(b.capture.oe.onaudioprocess=function(){},b.capture.oe.disconnect(),b.capture.oe=void 0);void 0!==b.capture.Fe&&(b.capture.Fe.disconnect(),b.capture.Fe=void 0);void 0!==b.capture.He&&(b.capture.He=void 0);b.capture=void 0}else void 0!=b.audio.oe&&(b.audio.oe.disconnect(),b.audio.oe=void 0),b.audio=void 0;void 0!==b.zd&&void 0===b.audio&&void 0===b.capture&&(b.zd.close(),b.zd=void 0)},63413:(a,b,c)=>{f.SDL2||(f.SDL2={});var d=f.SDL2;d.Xe!==f.canvas&&(d.te=f.createContext(f.canvas,
!1,!0),d.Xe=f.canvas);if(d.w!==a||d.ff!==b||d.hf!==d.te)d.image=d.te.createImageData(a,b),d.w=a,d.ff=b,d.hf=d.te;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=z[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.$e!==a&&(d.Ze=new Int32Array(a.buffer),d.af=new Uint8Array(a.buffer),d.$e=a),a=d.Ze,c=a.length,a.set(z.subarray(b,b+c)),a=d.af,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,
b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.te.putImageData(d.image,0,0)},64882:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var h=g.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=z[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=
4}else b=new Int32Array(b.buffer),n=b.length,b.set(z.subarray(e,e+n));h.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=E(c.length+1);x(c,d,c.length+1);return d},65871:a=>{f.canvas&&(f.canvas.style.cursor=t(a))},65954:()=>{f.canvas&&(f.canvas.style.cursor="none")},66023:()=>window.innerWidth,66053:()=>window.innerHeight};function Ja(a,b,c){a.addEventListener(b,c,{once:!0})}
function Fa(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&Ja(d,c,function(){"suspended"===a.state&&a.resume()})})})}function Ka(a){for(;0<a.length;)a.shift()(f)}function La(a){var b=Ma();a=a();Na(b);return a}function Ga(a,b){var c=f.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}
function Ha(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":y[a>>0]=b;break;case "i8":y[a>>0]=b;break;case "i16":oa[a>>1]=b;break;case "i32":z[a>>2]=b;break;case "i64":Ea=[b>>>0,(Da=b,1<=+Math.abs(Da)?0<Da?(Math.min(+Math.floor(Da/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Da-+(~~Da>>>0))/4294967296)>>>0:0)];z[a>>2]=Ea[0];z[a+4>>2]=Ea[1];break;case "float":B[a>>2]=b;break;case "double":C[a>>3]=b;break;case "*":A[a>>2]=b;break;default:p("invalid type for setValue: "+c)}}
function Oa(a,b){Pa=a;Qa=b;if(!F)return 1;Ra||(Ra=!0);if(0==a)G=function(){var d=Math.max(0,Sa+b-Ta())|0;setTimeout(Ua,d)};else if(1==a)G=function(){Va(Ua)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}G=function(){setImmediate(Ua)}}return 0}var Ta;Ta=()=>performance.now();
function Wa(a,b,c,d,e){!F||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");F=a;Xa=d;var g=H;Ra=!1;Ua=function(){if(!q)if(0<Ya.length){var h=Date.now(),m=Ya.shift();m.uf(m.qf);if(Za){var n=Za,r=0==n%1?n-1:Math.floor(n);Za=m.sf?r:(8*n+(r+.5))/9}ha('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||"Please wait...",
m=Za,n=$a.tf,m?m<n?f.setStatus(h+" ("+(n-m)+"/"+n+")"):f.setStatus(h):f.setStatus(""));g<H||setTimeout(Ua,0)}else g<H||(ab=ab+1|0,1==Pa&&1<Qa&&0!=ab%Qa?G():(0==Pa&&(Sa=Ta()),q||f.preMainLoop&&!1===f.preMainLoop()||(bb(a),f.postMainLoop&&f.postMainLoop()),g<H||("object"==typeof SDL&&SDL.audio&&SDL.audio.lf&&SDL.audio.lf(),G())))};e||(b&&0<b?Oa(0,1E3/b):Oa(1,1),G());if(c)throw"unwind";}function bb(a){if(!q)try{a()}catch(b){"unwind"!=b&&ea(1,b)}}
function cb(a,b){return setTimeout(function(){bb(a)},b)}function db(a){eb||(eb={});eb[a]||(eb[a]=1,l(a))}var eb,Ra=!1,G=null,H=0,F=null,Xa=0,Pa=0,Qa=0,ab=0,Ya=[];function fb(){H++;var a=Pa,b=Qa,c=F;F=null;Wa(c,0,!1,Xa,!0);Oa(a,b);G()}var $a={},Sa,Ua,Za,gb=!1,hb=!1,ib=[];
function jb(){function a(){hb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!kb){kb=!0;try{lb=!0}catch(c){lb=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}nb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:lb?null:l("warning: no BlobBuilder");ob="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Se||"undefined"!=typeof ob||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Se=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Se&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(lb)try{h=new Blob([c],{type:pb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:pb(d)}))}catch(r){db("Blob constructor present but fails: "+
r+"; falling back to blob builder")}h||(h=new nb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=ob.createObjectURL(h),n=new Image;n.onload=()=>{n.complete||p("Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);ob.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{ha("Image "+m+" could not be decoded");g&&g()};n.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.zf&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,g){function h(){n||(n=!0,e&&e(c))}function m(){n||(n=!0,new Audio,g&&g())}var n=!1;if(lb){try{var r=new Blob([c],{type:pb(d)})}catch(v){return m()}r=ob.createObjectURL(r);var u=new Audio;u.addEventListener("canplaythrough",function(){h(u)},!1);u.onerror=function(){if(!n){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var v="",P=0,K=0,qa=0;qa<c.length;qa++)for(P=P<<8|c[qa],K+=8;6<=K;){var mb=P>>K-6&63;K-=6;v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[mb]}2==
K?(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&3)<<4],v+="=="):4==K&&(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(P&15)<<2],v+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+v;h(u)}};u.src=r;cb(function(){h(u)},1E4)}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",function(c){!hb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function qb(a,b,c,d){if(b&&f.te&&a==f.canvas)return f.te;var e;if(b){var g={antialias:!1,alpha:!1,Re:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof rb&&(e=sb(a,g)))var m=I[e].ue}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof J||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.te=m,b&&tb(e),f.nf=b,ib.forEach(function(n){n()}),jb());return m}var ub=!1,vb=void 0,wb=void 0;
function xb(a,b){function c(){gb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=yb,vb&&d.requestPointerLock(),gb=!0,wb?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=A[SDL.screen>>2]|8388608),zb(f.canvas),Ab()):zb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),wb?("undefined"!=typeof SDL&&(z[SDL.screen>>2]=A[SDL.screen>>2]&
-8388609),zb(f.canvas),Ab()):zb(d));if(f.onFullScreen)f.onFullScreen(gb);if(f.onFullscreen)f.onFullscreen(gb)}vb=a;wb=b;"undefined"==typeof vb&&(vb=!0);"undefined"==typeof wb&&(wb=!1);var d=f.canvas;ub||(ub=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function yb(){if(!gb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Bb=0;function Va(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Bb)Bb=b+1E3/60;else for(;b+2>=Bb;)Bb+=1E3/60;setTimeout(a,Math.max(Bb-b,0))}}
function pb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Cb=[];function Ab(){var a=f.canvas;Cb.forEach(function(b){b(a.width,a.height)})}
function zb(a,b,c){b&&c?(a.pf=b,a.gf=c):(b=a.pf,c=a.gf);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}wb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Db={},kb,lb,nb,ob,L=12288,Eb=!1,Fb=0,Gb=0,Hb=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ib={},Jb;function Kb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function Lb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Mb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Nb=1,Ob=[],N=[],Pb=[],Qb=[],Rb=[],O=[],Sb=[],I=[],Q=[],Tb={},Ub=4;
function R(a){Vb||(Vb=a)}function Wb(a){for(var b=Nb++,c=a.length;c<b;c++)a[c]=null;return b}function sb(a,b){a.Ae||(a.Ae=a.getContext,a.getContext=function(d,e){e=a.Ae(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Xb(c,b):0}function Xb(a,b){var c=Wb(I),d={vf:c,attributes:b,version:b.Re,ue:a};a.canvas&&(a.canvas.xe=d);I[c]=d;("undefined"==typeof b.cf||b.cf)&&Yb(d);return c}function tb(a){Zb=I[a];f.te=J=Zb&&Zb.ue}
function Yb(a){a||(a=Zb);if(!a.jf){a.jf=!0;var b=a.ue;Kb(b);Lb(b);Mb(b);b.re=b.getExtension("EXT_disjoint_timer_query");b.yf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var rb={},Vb,Zb;function $b(a){var b=na(a)+1,c=E(b);c&&ma(a,y,c,b);return c}var ac=[];function bc(a,b){ac.length=0;var c;for(b>>=2;c=w[a++];)b+=105!=c&b,ac.push(105==c?z[b]:C[b++>>1]),++b;return ac}var cc=0;
function dc(){for(var a=S.length-1;0<=a;--a)ec(a);S=[];T=[]}var T=[];function fc(a,b,c){function d(h,m){if(h.length!=m.length)return!1;for(var n in h)if(h[n]!=m[n])return!1;return!0}for(var e in T){var g=T[e];if(g.Le==a&&d(g.Ne,c))return}T.push({Le:a,Ue:b,Ne:c});T.sort(function(h,m){return h.Ue<m.Ue})}function gc(a){for(var b=0;b<T.length;++b)T[b].Le==a&&(T.splice(b,1),--b)}function hc(){if(cc&&ic.we)for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.Le.apply(null,b.Ne)}}var S=[];
function ec(a){var b=S[a];b.target.removeEventListener(b.ne,b.df,b.pe);S.splice(a,1)}function U(a){function b(d){++cc;ic=a;hc();a.se(d);hc();--cc}if(a.qe)a.df=b,a.target.addEventListener(a.ne,b,a.pe),S.push(a),jc||(ta.push(dc),jc=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].ne==a.ne&&ec(c--)}function kc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function lc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var mc={},jc,ic,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc={},Ac=[0,document,window];function V(a){a=2<a?t(a):a;return Ac[a]||document.querySelector(a)}function Bc(a){return La(function(){var b=Cc(8),c=b+4,d=Cc(a.id.length+1);x(a.id,d,a.id.length+1);if(d=V(d))z[b>>2]=d.width,z[c>>2]=d.height;return[z[b>>2],z[c>>2]]})}function Dc(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Ec(a,b,c){a.rf?La(function(){var d=Cc(a.id.length+1);x(a.id,d,a.id.length+1);Dc(d,b,c)}):(a.width=b,a.height=c)}
function Fc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ec(a,d,e),a.style.width=g,a.style.height=h,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=u,a.style.paddingTop=v,a.style.paddingBottom=P,a.style.marginLeft=K,a.style.marginRight=
qa,a.style.marginTop=mb,a.style.marginBottom=yd,document.body.style.margin=zd,document.documentElement.style.overflow=Ad,document.body.scroll=Bd,a.style.ve=Cd,a.xe&&a.xe.ue.viewport(0,0,d,e),zc.Be&&W.apply(null,[zc.Be,37,0,zc.Oe]))}var c=Bc(a),d=c[0],e=c[1],g=a.style.width,h=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,u=a.style.paddingRight,v=a.style.paddingTop,P=a.style.paddingBottom,K=a.style.marginLeft,qa=a.style.marginRight,mb=a.style.marginTop,
yd=a.style.marginBottom,zd=document.body.style.margin,Ad=document.documentElement.style.overflow,Bd=document.body.scroll,Cd=a.style.ve;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Gc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Hc(a){return 0>Ac.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Ic(a,b){if(0!=b.Ke||0!=b.Ie){Fc(a);var c=b.mf?innerWidth:screen.width,d=b.mf?innerHeight:screen.height,e=Hc(a),g=e.width;e=e.height;var h=Bc(a),m=h[0];h=h[1];3==b.Ke?(Gc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Ke&&(c*h<m*d?(g=h*c/m,Gc(a,(d-g)/2,0),d=g):(g=m*d/h,Gc(a,0,(c-g)/2),c=g));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.ef&&(a.style.ve="optimizeSpeed",
a.style.ve="-moz-crisp-edges",a.style.ve="-o-crisp-edges",a.style.ve="-webkit-optimize-contrast",a.style.ve="optimize-contrast",a.style.ve="crisp-edges",a.style.ve="pixelated");g=2==b.Ie?devicePixelRatio:1;0!=b.Ie&&(c=c*g|0,d=d*g|0,Ec(a,c,d),a.xe&&a.xe.ue.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return lc()?-3:-1;zc=b;b.Be&&W.apply(null,[b.Be,37,0,b.Oe]);return 0}
function Jc(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Ge)a.Ge();else return document.body.requestPointerLock||document.body.Ge?-3:-1;return 0}
function Kc(a,b){C[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)C[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)C[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)z[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];z[a+1296>>2]=b.connected;z[a+1300>>2]=b.index;z[a+8>>2]=b.axes.length;z[a+12>>2]=b.buttons.length;x(b.id,a+1304,64);x(b.mapping,a+1368,64)}var Lc=[];
function Mc(a,b,c,d){for(var e=0;e<a;e++){var g=J[c](),h=g&&Wb(d);g?(g.name=h,d[h]=g):R(1282);z[b+4*e>>2]=h}}function Nc(a,b,c,d,e,g,h,m){b=N[b];if(a=J[a](b,c))d=m&&x(a.name,m,d),e&&(z[e>>2]=d),g&&(z[g>>2]=a.size),h&&(z[h>>2]=a.type)}function Oc(a,b){A[a>>2]=b;A[a+4>>2]=(b-A[a>>2])/4294967296}
function Pc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:y[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Oc(b,
d);break;case 0:z[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:y[b>>0]=d?1:0}}else R(1281)}function Qc(a){var b=na(a)+1,c=E(b);x(a,c,b);return c}function Rc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Sc(a){var b=a.ze,c=a.We,d;if(!b)for(a.ze=b={},a.Ve={},d=0;d<J.getProgramParameter(a,35718);++d){var e=J.getActiveUniform(a,d);var g=e.name;e=e.size;var h=Rc(g);h=0<h?g.slice(0,h):g;var m=a.Me;a.Me+=e;c[h]=[e,m];for(g=0;g<e;++g)b[m]=g,a.Ve[m++]=h}}
function X(a){var b=J.Ye;if(b){var c=b.ze[a];"number"==typeof c&&(b.ze[a]=c=J.getUniformLocation(b,b.Ve[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function Tc(a,b,c,d){if(c)if(a=N[a],Sc(a),a=J.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:z[c>>2]=a;break;case 2:B[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:z[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b]}else R(1281)}
function Uc(a,b,c,d){if(c)if(a=J.getVertexAttrib(a,b),34975==b)z[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:z[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:z[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:z[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:z[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function Vc(a,b,c,d,e){a-=5120;a=1==a?w:4==a?z:6==a?B:5==a||28922==a?A:pa;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Ub;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var Y=[],Wc=[];function Xc(a,b){if(!lc())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?cc&&ic.we?Ic(a,b):b.bf?(fc(Ic,1,[a,b]),1):-2:-3:-4}
function Yc(a,b){var c={target:V(2),ne:"beforeunload",qe:b,se:function(d){d=d||event;var e=W.apply(null,[b,28,0,a]);e&&(e=t(e));if(e)return d.preventDefault(),d.returnValue=e},pe:!0};U(c)}function Zc(a,b,c,d,e,g){oc||(oc=E(256));a={target:V(a),ne:g,qe:d,se:function(h){h=h||event;var m=h.target.id?h.target.id:"",n=oc;x(kc(h.target),n+0,128);x(m,n+128,128);W.apply(null,[d,e,n,b])&&h.preventDefault()},pe:c};U(a)}
function $c(a,b,c,d,e){qc||(qc=E(280));U({target:a,ne:e,qe:d,se:function(g){g=g||event;var h=qc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;z[h>>2]=n;z[h+4>>2]=lc();var r=n?m:pc,u=r&&r.id?r.id:"";x(kc(r),h+8,128);x(u,h+136,128);z[h+264>>2]=r?r.clientWidth:0;z[h+268>>2]=r?r.clientHeight:0;z[h+272>>2]=screen.width;z[h+276>>2]=screen.height;n&&(pc=m);W.apply(null,[d,19,h,b])&&g.preventDefault()},pe:c})}
function ad(a,b,c,d,e){rc||(rc=E(1432));b={target:V(2),we:!0,ne:e,qe:c,se:function(g){g=g||event;var h=rc;Kc(h,g.gamepad);W.apply(null,[c,d,h,a])&&g.preventDefault()},pe:b};U(b)}
function bd(a,b,c,d,e,g){sc||(sc=E(176));a={target:V(a),we:!0,ne:g,qe:d,se:function(h){var m=sc;C[m>>3]=h.timeStamp;var n=m>>2;z[n+2]=h.location;z[n+3]=h.ctrlKey;z[n+4]=h.shiftKey;z[n+5]=h.altKey;z[n+6]=h.metaKey;z[n+7]=h.repeat;z[n+8]=h.charCode;z[n+9]=h.keyCode;z[n+10]=h.which;x(h.key||"",m+44,32);x(h.code||"",m+76,32);x(h.char||"",m+108,32);x(h.locale||"",m+140,32);W.apply(null,[d,e,m,b])&&h.preventDefault()},pe:c};U(a)}
function cd(a,b,c){C[a>>3]=b.timeStamp;a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=b.altKey;z[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=Hc(c);z[a+13]=b.clientX-c.left;z[a+14]=b.clientY-c.top}
function dd(a,b,c,d,e,g){tc||(tc=E(72));a=V(a);U({target:a,we:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,ne:g,qe:d,se:function(h){h=h||event;cd(tc,h,a);W.apply(null,[d,e,tc,b])&&h.preventDefault()},pe:c})}function ed(a,b,c,d,e){uc||(uc=E(260));U({target:a,ne:e,qe:d,se:function(g){g=g||event;var h=uc,m=document.pointerLockElement||document.kf||document.Bf||document.Af;z[h>>2]=!!m;var n=m&&m.id?m.id:"";x(kc(m),h+4,128);x(n,h+132,128);W.apply(null,[d,20,h,b])&&g.preventDefault()},pe:c})}
function fd(a,b,c,d){vc||(vc=E(36));a=V(a);U({target:a,ne:"resize",qe:d,se:function(e){e=e||event;if(e.target==a){var g=document.body;if(g){var h=vc;z[h>>2]=e.detail;z[h+4>>2]=g.clientWidth;z[h+8>>2]=g.clientHeight;z[h+12>>2]=innerWidth;z[h+16>>2]=innerHeight;z[h+20>>2]=outerWidth;z[h+24>>2]=outerHeight;z[h+28>>2]=pageXOffset;z[h+32>>2]=pageYOffset;W.apply(null,[d,10,h,b])&&e.preventDefault()}}},pe:c})}
function gd(a,b,c,d,e,g){wc||(wc=E(1696));a=V(a);U({target:a,we:"touchstart"==g||"touchend"==g,ne:g,qe:d,se:function(h){for(var m,n={},r=h.touches,u=0;u<r.length;++u)m=r[u],m.Qe=m.Te=0,n[m.identifier]=m;for(u=0;u<h.changedTouches.length;++u)m=h.changedTouches[u],m.Qe=1,n[m.identifier]=m;for(u=0;u<h.targetTouches.length;++u)n[h.targetTouches[u].identifier].Te=1;r=wc;C[r>>3]=h.timeStamp;var v=r>>2;z[v+3]=h.ctrlKey;z[v+4]=h.shiftKey;z[v+5]=h.altKey;z[v+6]=h.metaKey;v+=7;var P=Hc(a),K=0;for(u in n)if(m=
n[u],z[v]=m.identifier,z[v+1]=m.screenX,z[v+2]=m.screenY,z[v+3]=m.clientX,z[v+4]=m.clientY,z[v+5]=m.pageX,z[v+6]=m.pageY,z[v+7]=m.Qe,z[v+8]=m.Te,z[v+9]=m.clientX-P.left,z[v+10]=m.clientY-P.top,v+=13,31<++K)break;z[r+8>>2]=K;W.apply(null,[d,e,r,b])&&h.preventDefault()},pe:c})}
function hd(a,b,c){var d=Ac[1];xc||(xc=E(8));U({target:d,ne:"visibilitychange",qe:c,se:function(e){e=e||event;var g=xc,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);z[g>>2]=document.hidden;z[g+4>>2]=h;W.apply(null,[c,21,g,a])&&e.preventDefault()},pe:b})}
function jd(a,b,c,d){yc||(yc=E(104));U({target:a,we:!0,ne:"wheel",qe:d,se:function(e){e=e||event;var g=yc;cd(g,e,a);C[g+72>>3]=e.deltaX;C[g+80>>3]=e.deltaY;C[g+88>>3]=e.deltaZ;z[g+96>>2]=e.deltaMode;W.apply(null,[d,9,g,b])&&e.preventDefault()},pe:c})}var kd={};
function ld(){if(!md){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in kd)void 0===kd[b]?delete a[b]:a[b]=kd[b];var c=[];for(b in a)c.push(b+"="+a[b]);md=c}return md}var md,nd=[null,[],[]];function od(a){try{a()}catch(b){p(b)}}var pd=0,qd=null,rd=0,sd=[],td={},ud={},vd=0,wd=null,xd=[];
function Dd(a){var b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"==typeof e?function(){sd.push(d);try{return e.apply(null,arguments)}finally{q||(sd.pop()===d||p(),qd&&1===pd&&0===sd.length&&(pd=0,od(Ed),"undefined"!=typeof Fibers&&Fibers.Cf()))}}:e})(c);return b}function Fd(){var a=E(4108),b=a+12;z[a>>2]=b;z[a+4>>2]=b+4096;b=sd[0];var c=td[b];void 0===c&&(c=vd++,td[b]=c,ud[c]=b);z[a+8>>2]=c;return a}
function Gd(a){if(!q){if(0===pd){var b=!1,c=!1;a(d=>{if(!q&&(rd=d||0,b=!0,c)){pd=2;od(()=>Hd(qd));"undefined"!=typeof Db&&F&&fb();d=!1;try{var e=(0,f.asm[ud[z[qd+8>>2]]])()}catch(m){e=m,d=!0}var g=!1;if(!qd){var h=wd;h&&(wd=null,(d?h.reject:h.resolve)(e),g=!0)}if(d&&!g)throw e;}});c=!0;b||(pd=1,qd=Fd(),"undefined"!=typeof Db&&F&&(G=null,H++),od(()=>Id(qd)))}else 2===pd?(pd=0,od(Jd),Kd(qd),qd=null,xd.forEach(d=>bb(d))):p("invalid state: "+pd);return rd}}f.requestFullscreen=function(a,b){xb(a,b)};
f.requestAnimationFrame=function(a){Va(a)};f.setCanvasSize=function(a,b,c){zb(f.canvas,a,b);c||Ab()};f.pauseMainLoop=function(){G=null;H++};f.resumeMainLoop=function(){fb()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return qb(a,b,c,d)};for(var J,Z=0;32>Z;++Z)Lc.push(Array(Z));var Ld=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Ld.subarray(0,Z+1);var Md=new Int32Array(288);
for(Z=0;288>Z;++Z)Wc[Z]=Md.subarray(0,Z+1);
var Nd={J:function(){return 0},Ta:function(){return 0},Ua:function(){},Wa:function(){return Date.now()},Va:function(){return!0},f:function(){p("")},Ia:function(a){if(12448==a)return L=12288,1;L=12300;return 0},jc:function(a,b,c,d,e){if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=z[b>>2];if(12321==a)M.alpha=0<z[b+4>>2];else if(12325==a)M.depth=0<z[b+4>>2];else if(12326==a)M.stencil=0<z[b+4>>2];else if(12337==a)a=z[b+4>>2],M.antialias=0<a;else if(12338==a)a=z[b+4>>2],M.antialias=1==a;else if(12544==a)M.wf=
12547!=z[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(z[e>>2]=1),c&&0<d&&(z[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},Pb:function(a,b,c,d){if(62E3!=a)return L=12296,0;for(a=1;;){b=z[d>>2];if(12440==b)a=z[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.Re=a-1;M.xf=0;Jb=sb(f.canvas,M);if(0!=Jb)return L=12288,tb(Jb),f.nf=!0,ib.forEach(function(e){e()}),tb(null),62004;L=12297;return 0},sb:function(a,b){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,
0;L=12288;return 62006},Eb:function(a,b){if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=Jb;Zb===I[a]&&(Zb=null);if("object"==typeof mc)for(var c=I[a].ue.canvas,d=0;d<S.length;++d)S[d].target!=c||ec(d--);I[a]&&I[a].ue.canvas&&(I[a].ue.canvas.xe=void 0);I[a]=null;L=12288;Fb==b&&(Fb=0);return 1},hb:function(a,b){if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Gb==b&&(Gb=0);Hb==b&&(Hb=0);L=12288;return 1},_b:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,
0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return z[d>>2]=M.alpha?32:24,1;case 12321:return z[d>>2]=M.alpha?8:0,1;case 12322:return z[d>>2]=8,1;case 12323:return z[d>>2]=8,1;case 12324:return z[d>>2]=8,1;case 12325:return z[d>>2]=M.depth?24:0,1;case 12326:return z[d>>2]=M.stencil?8:0,1;case 12327:return z[d>>2]=12344,1;case 12328:return z[d>>2]=62002,1;case 12329:return z[d>>2]=0,1;case 12330:return z[d>>2]=4096,1;case 12331:return z[d>>2]=16777216,1;case 12332:return z[d>>2]=4096,1;case 12333:return z[d>>
2]=0,1;case 12334:return z[d>>2]=0,1;case 12335:return z[d>>2]=12344,1;case 12337:return z[d>>2]=M.antialias?4:0,1;case 12338:return z[d>>2]=M.antialias?1:0,1;case 12339:return z[d>>2]=4,1;case 12340:return z[d>>2]=12344,1;case 12341:case 12342:case 12343:return z[d>>2]=-1,1;case 12345:case 12346:return z[d>>2]=0,1;case 12347:return z[d>>2]=0,1;case 12348:return z[d>>2]=1;case 12349:case 12350:return z[d>>2]=0,1;case 12351:return z[d>>2]=12430,1;case 12352:return z[d>>2]=4,1;case 12354:return z[d>>
2]=0,1;default:return L=12292,0}},K:function(){L=12288;return 62E3},Ga:function(){return L},Fc:function(a,b,c){if(62E3==a)return b&&(z[b>>2]=1),c&&(z[c>>2]=4),Eb=!0,L=12288,1;L=12296;return 0},Ya:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;tb(d?Jb:null);Fb=d;Hb=b;Gb=c;L=12288;return 1},Ha:function(a,b){if(62E3!=a)return L=12296,0;L=12288;if(Ib[b])return Ib[b];switch(b){case 12371:a=$b("Emscripten");break;case 12372:a=
$b("1.4 Emscripten EGL");break;case 12373:a=$b("");break;case 12429:a=$b("OpenGL_ES");break;default:return L=12300,0}return Ib[b]=a},Qa:function(){if(Eb)if(f.te)if(f.te.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},La:function(a,b){if(62E3!=a)return L=12296,0;0==b?Oa(0,0):Oa(1,b);L=12288;return 1},uc:function(a){if(62E3!=a)return L=12296,0;Hb=Gb=Fb=0;Eb=!1;L=12288;return 1},Ja:function(){L=12288;return 1},Ka:function(){L=12288;return 1},Da:function(a,b,c){b=bc(b,
c);return Ia[a].apply(null,b)},a:function(a,b,c){b=bc(b,c);return Ia[a].apply(null,b)},tb:function(){G=null;H++;F=null},Aa:function(){if(!lc())return-1;gc(Ic);var a=Ac[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ea:function(){gc(Jc);if(document.exitPointerLock)document.exitPointerLock();else if(document.Ae)document.Ae();else return-1;return 0},d:function(){return devicePixelRatio},
b:function(a,b,c){a=V(a);if(!a)return-4;a=Hc(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},da:function(a,b){if(0>a||a>=nc.length)return-5;if(!nc[a])return-7;Kc(b,nc[a]);return 0},j:Ta,oa:function(){return nc.length},Fa:function(a,b){z[a>>2]=screen.width;z[b>>2]=screen.height},ea:function(a){J.activeTexture(a)},ca:function(a,b){J.attachShader(N[a],O[b])},va:function(a,b){J.re.beginQueryEXT(a,Q[b])},ba:function(a,b,c){J.bindAttribLocation(N[a],b,t(c))},aa:function(a,b){J.bindBuffer(a,Ob[b])},$:function(a,
b){J.bindFramebuffer(a,Pb[b])},_:function(a,b){J.bindRenderbuffer(a,Qb[b])},Z:function(a,b){J.bindTexture(a,Rb[b])},ma:function(a){J.bindVertexArray(Sb[a])},Y:function(a,b,c,d){J.blendColor(a,b,c,d)},X:function(a){J.blendEquation(a)},W:function(a,b){J.blendEquationSeparate(a,b)},V:function(a,b){J.blendFunc(a,b)},U:function(a,b,c,d){J.blendFuncSeparate(a,b,c,d)},T:function(a,b,c,d){J.bufferData(a,c?w.subarray(c,c+b):b,d)},S:function(a,b,c,d){J.bufferSubData(a,b,w.subarray(d,d+c))},R:function(a){return J.checkFramebufferStatus(a)},
Q:function(a){J.clear(a)},P:function(a,b,c,d){J.clearColor(a,b,c,d)},O:function(a){J.clearDepth(a)},N:function(a){J.clearStencil(a)},M:function(a,b,c,d){J.colorMask(!!a,!!b,!!c,!!d)},L:function(a){J.compileShader(O[a])},rd:function(a,b,c,d,e,g,h,m){J.compressedTexImage2D(a,b,c,d,e,g,m?w.subarray(m,m+h):null)},qd:function(a,b,c,d,e,g,h,m,n){J.compressedTexSubImage2D(a,b,c,d,e,g,h,n?w.subarray(n,n+m):null)},pd:function(a,b,c,d,e,g,h,m){J.copyTexImage2D(a,b,c,d,e,g,h,m)},od:function(a,b,c,d,e,g,h,m){J.copyTexSubImage2D(a,
b,c,d,e,g,h,m)},nd:function(){var a=Wb(N),b=J.createProgram();b.name=a;b.Ee=b.Ce=b.De=0;b.Me=1;N[a]=b;return a},md:function(a){var b=Wb(O);O[b]=J.createShader(a);return b},ld:function(a){J.cullFace(a)},kd:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Ob[d];e&&(J.deleteBuffer(e),e.name=0,Ob[d]=null)}},jd:function(a,b){for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=Pb[d];e&&(J.deleteFramebuffer(e),e.name=0,Pb[d]=null)}},id:function(a){if(a){var b=N[a];b?(J.deleteProgram(b),b.name=0,N[a]=null):R(1281)}},
xa:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Q[d];e&&(J.re.deleteQueryEXT(e),Q[d]=null)}},hd:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Qb[d];e&&(J.deleteRenderbuffer(e),e.name=0,Qb[d]=null)}},gd:function(a){if(a){var b=O[a];b?(J.deleteShader(b),O[a]=null):R(1281)}},fd:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=Rb[d];e&&(J.deleteTexture(e),e.name=0,Rb[d]=null)}},la:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2];J.deleteVertexArray(Sb[d]);Sb[d]=null}},ed:function(a){J.depthFunc(a)},
dd:function(a){J.depthMask(!!a)},cd:function(a,b){J.depthRange(a,b)},bd:function(a,b){J.detachShader(N[a],O[b])},ad:function(a){J.disable(a)},$c:function(a){J.disableVertexAttribArray(a)},_c:function(a,b,c){J.drawArrays(a,b,c)},ha:function(a,b,c,d){J.drawArraysInstanced(a,b,c,d)},ia:function(a,b){for(var c=Lc[a],d=0;d<a;d++)c[d]=z[b+4*d>>2];J.drawBuffers(c)},Zc:function(a,b,c,d){J.drawElements(a,b,c,d)},ga:function(a,b,c,d,e){J.drawElementsInstanced(a,b,c,d,e)},Yc:function(a){J.enable(a)},Xc:function(a){J.enableVertexAttribArray(a)},
ua:function(a){J.re.endQueryEXT(a)},Wc:function(){J.finish()},Vc:function(){J.flush()},Uc:function(a,b,c,d){J.framebufferRenderbuffer(a,b,c,Qb[d])},Tc:function(a,b,c,d,e){J.framebufferTexture2D(a,b,c,Rb[d],e)},Sc:function(a){J.frontFace(a)},Rc:function(a,b){Mc(a,b,"createBuffer",Ob)},Pc:function(a,b){Mc(a,b,"createFramebuffer",Pb)},ya:function(a,b){for(var c=0;c<a;c++){var d=J.re.createQueryEXT();if(!d){for(R(1282);c<a;)z[b+4*c++>>2]=0;break}var e=Wb(Q);d.name=e;Q[e]=d;z[b+4*c>>2]=e}},Oc:function(a,
b){Mc(a,b,"createRenderbuffer",Qb)},Nc:function(a,b){Mc(a,b,"createTexture",Rb)},ka:function(a,b){Mc(a,b,"createVertexArray",Sb)},Qc:function(a){J.generateMipmap(a)},Mc:function(a,b,c,d,e,g,h){Nc("getActiveAttrib",a,b,c,d,e,g,h)},Lc:function(a,b,c,d,e,g,h){Nc("getActiveUniform",a,b,c,d,e,g,h)},Kc:function(a,b,c,d){a=J.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);z[c>>2]=e;for(b=0;b<e;++b)z[d+4*b>>2]=O.indexOf(a[b])},Jc:function(a,b){return J.getAttribLocation(N[a],t(b))},Ic:function(a,b){Pc(a,
b,4)},Hc:function(a,b,c){c?z[c>>2]=J.getBufferParameter(a,b):R(1281)},Gc:function(){var a=J.getError()||Vb;Vb=0;return a},Ec:function(a,b){Pc(a,b,2)},Dc:function(a,b,c,d){a=J.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;z[d>>2]=a},Cc:function(a,b){Pc(a,b,0)},Ac:function(a,b,c,d){a=J.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?x(a,d,b):0;c&&(z[c>>2]=b)},Bc:function(a,b,c){if(c)if(a>=Nb)R(1281);else if(a=N[a],35716==
b)a=J.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.Ee)for(b=0;b<J.getProgramParameter(a,35718);++b)a.Ee=Math.max(a.Ee,J.getActiveUniform(a,b).name.length+1);z[c>>2]=a.Ee}else if(35722==b){if(!a.Ce)for(b=0;b<J.getProgramParameter(a,35721);++b)a.Ce=Math.max(a.Ce,J.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.Ce}else if(35381==b){if(!a.De)for(b=0;b<J.getProgramParameter(a,35382);++b)a.De=Math.max(a.De,J.getActiveUniformBlockName(a,b).length+1);z[c>>
2]=a.De}else z[c>>2]=J.getProgramParameter(a,b);else R(1281)},pa:function(a,b,c){if(c){a=J.re.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Oc(c,d)}else R(1281)},ra:function(a,b,c){if(c){a=J.re.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z[c>>2]=d}else R(1281)},na:function(a,b,c){if(c){a=J.re.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Oc(c,d)}else R(1281)},qa:function(a,b,c){if(c){a=J.re.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;z[c>>2]=d}else R(1281)},sa:function(a,b,c){c?z[c>>2]=J.re.getQueryEXT(a,b):R(1281)},zc:function(a,b,c){c?z[c>>2]=J.getRenderbufferParameter(a,b):R(1281)},xc:function(a,b,c,d){a=J.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?x(a,d,b):0;c&&(z[c>>2]=b)},wc:function(a,b,c,d){a=J.getShaderPrecisionFormat(a,b);z[c>>2]=a.rangeMin;z[c+4>>2]=a.rangeMax;z[d>>2]=a.precision},vc:function(a,b,c,d){if(a=J.getShaderSource(O[a]))b=0<b&&d?x(a,d,b):0,c&&(z[c>>2]=b)},yc:function(a,b,c){c?
35716==b?(a=J.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=J.getShaderSource(O[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=J.getShaderParameter(O[a],b):R(1281)},tc:function(a){var b=Tb[a];if(!b){switch(a){case 7939:b=J.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Qc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||R(1280);b=b&&Qc(b);break;case 7938:b=Qc("OpenGL ES 2.0 ("+J.getParameter(7938)+")");
break;case 35724:b=J.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Qc(b);break;default:R(1280)}Tb[a]=b}return b},sc:function(a,b,c){c?B[c>>2]=J.getTexParameter(a,b):R(1281)},rc:function(a,b,c){c?z[c>>2]=J.getTexParameter(a,b):R(1281)},oc:function(a,b){b=t(b);if(a=N[a]){Sc(a);var c=a.ze,d=0,e=b,g=Rc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.We[e])&&d<e[0]&&(d+=e[1],
c[d]=c[d]||J.getUniformLocation(a,b)))return d}else R(1281);return-1},qc:function(a,b,c){Tc(a,b,c,2)},pc:function(a,b,c){Tc(a,b,c,0)},lc:function(a,b,c){c?z[c>>2]=J.getVertexAttribOffset(a,b):R(1281)},nc:function(a,b,c){Uc(a,b,c,2)},mc:function(a,b,c){Uc(a,b,c,5)},kc:function(a,b){J.hint(a,b)},ic:function(a){return(a=Ob[a])?J.isBuffer(a):0},hc:function(a){return J.isEnabled(a)},gc:function(a){return(a=Pb[a])?J.isFramebuffer(a):0},fc:function(a){return(a=N[a])?J.isProgram(a):0},wa:function(a){return(a=
Q[a])?J.re.isQueryEXT(a):0},ec:function(a){return(a=Qb[a])?J.isRenderbuffer(a):0},dc:function(a){return(a=O[a])?J.isShader(a):0},cc:function(a){return(a=Rb[a])?J.isTexture(a):0},ja:function(a){return(a=Sb[a])?J.isVertexArray(a):0},bc:function(a){J.lineWidth(a)},ac:function(a){a=N[a];J.linkProgram(a);a.ze=0;a.We={}},$b:function(a,b){3317==a&&(Ub=b);J.pixelStorei(a,b)},Zb:function(a,b){J.polygonOffset(a,b)},ta:function(a,b){J.re.queryCounterEXT(Q[a],b)},Yb:function(a,b,c,d,e,g,h){(h=Vc(g,e,c,d,h))?
J.readPixels(a,b,c,d,e,g,h):R(1280)},Xb:function(){},Wb:function(a,b,c,d){J.renderbufferStorage(a,b,c,d)},Vb:function(a,b){J.sampleCoverage(a,!!b)},Ub:function(a,b,c,d){J.scissor(a,b,c,d)},Tb:function(){R(1280)},Sb:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?z[d+4*g>>2]:-1;e+=t(z[c+4*g>>2],0>h?void 0:h)}J.shaderSource(O[a],e)},Rb:function(a,b,c){J.stencilFunc(a,b,c)},Qb:function(a,b,c,d){J.stencilFuncSeparate(a,b,c,d)},Ob:function(a){J.stencilMask(a)},Nb:function(a,b){J.stencilMaskSeparate(a,
b)},Mb:function(a,b,c){J.stencilOp(a,b,c)},Lb:function(a,b,c,d){J.stencilOpSeparate(a,b,c,d)},Kb:function(a,b,c,d,e,g,h,m,n){J.texImage2D(a,b,c,d,e,g,h,m,n?Vc(m,h,d,e,n):null)},Jb:function(a,b,c){J.texParameterf(a,b,c)},Ib:function(a,b,c){J.texParameterf(a,b,B[c>>2])},Hb:function(a,b,c){J.texParameteri(a,b,c)},Gb:function(a,b,c){J.texParameteri(a,b,z[c>>2])},Fb:function(a,b,c,d,e,g,h,m,n){var r=null;n&&(r=Vc(m,h,e,g,n));J.texSubImage2D(a,b,c,d,e,g,h,m,r)},Db:function(a,b){J.uniform1f(X(a),b)},Cb:function(a,
b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);J.uniform1fv(X(a),d)},Bb:function(a,b){J.uniform1i(X(a),b)},Ab:function(a,b,c){if(288>=b)for(var d=Wc[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);J.uniform1iv(X(a),d)},zb:function(a,b,c){J.uniform2f(X(a),b,c)},yb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);J.uniform2fv(X(a),d)},xb:function(a,b,
c){J.uniform2i(X(a),b,c)},wb:function(a,b,c){if(144>=b)for(var d=Wc[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);J.uniform2iv(X(a),d)},vb:function(a,b,c,d){J.uniform3f(X(a),b,c,d)},ub:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);J.uniform3fv(X(a),d)},rb:function(a,b,c,d){J.uniform3i(X(a),b,c,d)},qb:function(a,b,c){if(96>=b)for(var d=Wc[3*
b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);J.uniform3iv(X(a),d)},pb:function(a,b,c,d,e){J.uniform4f(X(a),b,c,d,e)},ob:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=B;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=B.subarray(c>>2,c+16*b>>2);J.uniform4fv(X(a),d)},nb:function(a,b,c,d,e){J.uniform4i(X(a),b,c,d,e)},mb:function(a,b,c){if(72>=b)for(var d=Wc[4*b-1],e=0;e<4*b;e+=4)d[e]=
z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2],d[e+3]=z[c+(4*e+12)>>2];else d=z.subarray(c>>2,c+16*b>>2);J.uniform4iv(X(a),d)},lb:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],g=0;g<4*b;g+=4)e[g]=B[d+4*g>>2],e[g+1]=B[d+(4*g+4)>>2],e[g+2]=B[d+(4*g+8)>>2],e[g+3]=B[d+(4*g+12)>>2];else e=B.subarray(d>>2,d+16*b>>2);J.uniformMatrix2fv(X(a),!!c,e)},kb:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],g=0;g<9*b;g+=9)e[g]=B[d+4*g>>2],e[g+1]=B[d+(4*g+4)>>2],e[g+2]=B[d+(4*g+8)>>2],e[g+3]=B[d+(4*g+12)>>
2],e[g+4]=B[d+(4*g+16)>>2],e[g+5]=B[d+(4*g+20)>>2],e[g+6]=B[d+(4*g+24)>>2],e[g+7]=B[d+(4*g+28)>>2],e[g+8]=B[d+(4*g+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);J.uniformMatrix3fv(X(a),!!c,e)},jb:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],g=B;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;e[h]=g[m];e[h+1]=g[m+1];e[h+2]=g[m+2];e[h+3]=g[m+3];e[h+4]=g[m+4];e[h+5]=g[m+5];e[h+6]=g[m+6];e[h+7]=g[m+7];e[h+8]=g[m+8];e[h+9]=g[m+9];e[h+10]=g[m+10];e[h+11]=g[m+11];e[h+12]=g[m+12];e[h+13]=g[m+13];e[h+14]=g[m+14];e[h+
15]=g[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(X(a),!!c,e)},ib:function(a){a=N[a];J.useProgram(a);J.Ye=a},gb:function(a){J.validateProgram(N[a])},fb:function(a,b){J.vertexAttrib1f(a,b)},eb:function(a,b){J.vertexAttrib1f(a,B[b>>2])},db:function(a,b,c){J.vertexAttrib2f(a,b,c)},cb:function(a,b){J.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},bb:function(a,b,c,d){J.vertexAttrib3f(a,b,c,d)},ab:function(a,b){J.vertexAttrib3f(a,B[b>>2],B[b+4>>2],B[b+8>>2])},$a:function(a,b,c,d,e){J.vertexAttrib4f(a,
b,c,d,e)},_a:function(a,b){J.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},fa:function(a,b){J.vertexAttribDivisor(a,b)},Za:function(a,b,c,d,e,g){J.vertexAttribPointer(a,b,c,!!d,e,g)},Xa:function(a,b,c,d){J.viewport(a,b,c,d)},l:function(){return 1},Pa:function(a,b,c){w.copyWithin(a,b,b+c)},Ba:function(a,b,c){return Xc(a,{Ke:z[c>>2],Ie:z[c+4>>2],ef:z[c+8>>2],bf:b,Be:z[c+12>>2],Oe:z[c+16>>2]})},G:function(a,b){a=V(a);return a?a.requestPointerLock||a.Ge?cc&&ic.we?Jc(a):b?(fc(Jc,2,[a]),1):
-2:-1:-4},i:function(){p("OOM")},za:function(){return(nc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},m:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;Yc(a,b);return 0},y:function(a,b,c,d){Zc(a,b,c,d,12,"blur");return 0},c:Dc,h:function(a,b,c){a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},z:function(a,b,c,d){Zc(a,b,c,d,13,"focus");return 0},p:function(a,b,c,d){if(!lc())return-1;
a=V(a);if(!a)return-4;$c(a,b,c,d,"fullscreenchange");$c(a,b,c,d,"webkitfullscreenchange");return 0},e:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;ad(a,b,c,26,"gamepadconnected");return 0},g:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;ad(a,b,c,27,"gamepaddisconnected");return 0},s:function(a,b,c,d){bd(a,b,c,d,2,"keydown");return 0},q:function(a,b,c,d){bd(a,b,c,d,1,"keypress");return 0},r:function(a,b,c,d){bd(a,b,c,d,3,"keyup");
return 0},td:function(a,b,c){Wa(function(){dynCall_v.call(null,a)},b,c)},sd:Oa,E:function(a,b,c,d){dd(a,b,c,d,5,"mousedown");return 0},C:function(a,b,c,d){dd(a,b,c,d,33,"mouseenter");return 0},B:function(a,b,c,d){dd(a,b,c,d,34,"mouseleave");return 0},F:function(a,b,c,d){dd(a,b,c,d,8,"mousemove");return 0},D:function(a,b,c,d){dd(a,b,c,d,6,"mouseup");return 0},t:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Ae||document.body.kf||document.body.Ge))return-1;
a=V(a);if(!a)return-4;ed(a,b,c,d,"pointerlockchange");ed(a,b,c,d,"mozpointerlockchange");ed(a,b,c,d,"webkitpointerlockchange");ed(a,b,c,d,"mspointerlockchange");return 0},o:function(a,b,c,d){fd(a,b,c,d);return 0},u:function(a,b,c,d){gd(a,b,c,d,25,"touchcancel");return 0},w:function(a,b,c,d){gd(a,b,c,d,23,"touchend");return 0},v:function(a,b,c,d){gd(a,b,c,d,24,"touchmove");return 0},x:function(a,b,c,d){gd(a,b,c,d,22,"touchstart");return 0},n:function(a,b,c){hd(a,b,c);return 0},A:function(a,b,c,d){a=
V(a);return"undefined"!=typeof a.onwheel?(jd(a,b,c,d),0):-1},Ca:function(a){fa(t(a))},k:function(a){return Gd(b=>cb(b,a))},Na:function(a,b){var c=0;ld().forEach(function(d,e){var g=b+c;e=A[a+4*e>>2]=g;for(g=0;g<d.length;++g)y[e++>>0]=d.charCodeAt(g);y[e>>0]=0;c+=d.length+1});return 0},Oa:function(a,b){var c=ld();A[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A[b>>2]=d;return 0},I:function(){return 52},Sa:function(){return 52},Ma:function(){return 70},Ra:function(a,b,c,d){for(var e=
0,g=0;g<c;g++){var h=A[b>>2],m=A[b+4>>2];b+=8;for(var n=0;n<m;n++){var r=w[h+n],u=nd[a];0===r||10===r?((1===a?ha:l)(la(u,0)),u.length=0):u.push(r)}e+=m}A[d>>2]=e;return 0},H:function(){}};
(function(){function a(g){g=g.exports;g=Dd(g);f.asm=g;ja=f.asm.ud;g=ja.buffer;f.HEAP8=y=new Int8Array(g);f.HEAP16=oa=new Int16Array(g);f.HEAP32=z=new Int32Array(g);f.HEAPU8=w=new Uint8Array(g);f.HEAPU16=pa=new Uint16Array(g);f.HEAPU32=A=new Uint32Array(g);f.HEAPF32=B=new Float32Array(g);f.HEAPF64=C=new Float64Array(g);sa.unshift(f.asm.vd);wa--;f.monitorRunDependencies&&f.monitorRunDependencies(wa);0==wa&&(null!==xa&&(clearInterval(xa),xa=null),ya&&(g=ya,ya=null,g()))}function b(g){a(g.instance)}function c(g){return Ca().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(g,function(h){l("failed to asynchronously prepare wasm: "+h);p(h)})}var d={a:Nd};wa++;f.monitorRunDependencies&&f.monitorRunDependencies(wa);if(f.instantiateWasm)try{var e=f.instantiateWasm(d,a);return e=Dd(e)}catch(g){return l("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return ia||"function"!=typeof WebAssembly.instantiateStreaming||za()||"function"!=typeof fetch?c(b):fetch(D,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,
d).then(b,function(h){l("wasm streaming compile failed: "+h);l("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.vd).apply(null,arguments)};f._playTromino=function(){return(f._playTromino=f.asm.wd).apply(null,arguments)};
var Kd=f._free=function(){return(Kd=f._free=f.asm.xd).apply(null,arguments)},E=f._malloc=function(){return(E=f._malloc=f.asm.yd).apply(null,arguments)},Ma=f.stackSave=function(){return(Ma=f.stackSave=f.asm.Ad).apply(null,arguments)},Na=f.stackRestore=function(){return(Na=f.stackRestore=f.asm.Bd).apply(null,arguments)},Cc=f.stackAlloc=function(){return(Cc=f.stackAlloc=f.asm.Cd).apply(null,arguments)},dynCall_vi=f.dynCall_vi=function(){return(dynCall_vi=f.dynCall_vi=f.asm.Dd).apply(null,arguments)},
dynCall_iii=f.dynCall_iii=function(){return(dynCall_iii=f.dynCall_iii=f.asm.Ed).apply(null,arguments)},dynCall_v=f.dynCall_v=function(){return(dynCall_v=f.dynCall_v=f.asm.Fd).apply(null,arguments)};f.dynCall_viiii=function(){return(f.dynCall_viiii=f.asm.Gd).apply(null,arguments)};f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.Hd).apply(null,arguments)};var W=f.dynCall_iiii=function(){return(W=f.dynCall_iiii=f.asm.Id).apply(null,arguments)};
f.dynCall_viii=function(){return(f.dynCall_viii=f.asm.Jd).apply(null,arguments)};var dynCall_vii=f.dynCall_vii=function(){return(dynCall_vii=f.dynCall_vii=f.asm.Kd).apply(null,arguments)};f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.Ld).apply(null,arguments)};f.dynCall_iiiiiiii=function(){return(f.dynCall_iiiiiiii=f.asm.Md).apply(null,arguments)};f.dynCall_iiiiiiiiii=function(){return(f.dynCall_iiiiiiiiii=f.asm.Nd).apply(null,arguments)};
f.dynCall_iiiii=function(){return(f.dynCall_iiiii=f.asm.Od).apply(null,arguments)};f.dynCall_iiiiiiiiiiiiiiff=function(){return(f.dynCall_iiiiiiiiiiiiiiff=f.asm.Pd).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.Qd).apply(null,arguments)};f.dynCall_ji=function(){return(f.dynCall_ji=f.asm.Rd).apply(null,arguments)};f.dynCall_viiiii=function(){return(f.dynCall_viiiii=f.asm.Sd).apply(null,arguments)};
f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.Td).apply(null,arguments)};f.dynCall_viiiiiii=function(){return(f.dynCall_viiiiiii=f.asm.Ud).apply(null,arguments)};f.dynCall_viiiiiiiiiii=function(){return(f.dynCall_viiiiiiiiiii=f.asm.Vd).apply(null,arguments)};f.dynCall_iiiiiidiiff=function(){return(f.dynCall_iiiiiidiiff=f.asm.Wd).apply(null,arguments)};f.dynCall_i=function(){return(f.dynCall_i=f.asm.Xd).apply(null,arguments)};
f.dynCall_vffff=function(){return(f.dynCall_vffff=f.asm.Yd).apply(null,arguments)};f.dynCall_vf=function(){return(f.dynCall_vf=f.asm.Zd).apply(null,arguments)};f.dynCall_viiiiiiii=function(){return(f.dynCall_viiiiiiii=f.asm._d).apply(null,arguments)};f.dynCall_viiiiiiiii=function(){return(f.dynCall_viiiiiiiii=f.asm.$d).apply(null,arguments)};f.dynCall_vff=function(){return(f.dynCall_vff=f.asm.ae).apply(null,arguments)};f.dynCall_vfi=function(){return(f.dynCall_vfi=f.asm.be).apply(null,arguments)};
f.dynCall_viif=function(){return(f.dynCall_viif=f.asm.ce).apply(null,arguments)};f.dynCall_vif=function(){return(f.dynCall_vif=f.asm.de).apply(null,arguments)};f.dynCall_viff=function(){return(f.dynCall_viff=f.asm.ee).apply(null,arguments)};f.dynCall_vifff=function(){return(f.dynCall_vifff=f.asm.fe).apply(null,arguments)};f.dynCall_viffff=function(){return(f.dynCall_viffff=f.asm.ge).apply(null,arguments)};f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.he).apply(null,arguments)};
f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.ie).apply(null,arguments)};
var Id=f._asyncify_start_unwind=function(){return(Id=f._asyncify_start_unwind=f.asm.je).apply(null,arguments)},Ed=f._asyncify_stop_unwind=function(){return(Ed=f._asyncify_stop_unwind=f.asm.ke).apply(null,arguments)},Hd=f._asyncify_start_rewind=function(){return(Hd=f._asyncify_start_rewind=f.asm.le).apply(null,arguments)},Jd=f._asyncify_stop_rewind=function(){return(Jd=f._asyncify_stop_rewind=f.asm.me).apply(null,arguments)},Od;ya=function Pd(){Od||Qd();Od||(ya=Pd)};
function Qd(){function a(){if(!Od&&(Od=!0,f.calledRun=!0,!q)){Ka(sa);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();ua.unshift(b)}Ka(ua)}}if(!(0<wa)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)va();Ka(ra);0<wa||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Qd();


  return createTrmnMod.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createTrmnMod;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createTrmnMod; });
else if (typeof exports === 'object')
  exports["createTrmnMod"] = createTrmnMod;
