name: Emscripten build for WebAssembly

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out Emscripten repository
      uses: actions/checkout@v2
      with:
        repository: emscripten-core/emsdk
        path: emsdk

    - name: Install Emscripten SDK
      run: |
        ./emsdk install latest
        ./emsdk activate latest
      working-directory: emsdk

    - name: Check out main repository
      uses: actions/checkout@v2
      with:
        path: tromino-puzzle

    - name: Make
      run: |
        source ${{ github.workspace }}/emsdk/emsdk_env.sh
        emmake make
      working-directory: tromino-puzzle/emscripten

    - name: Archive web app artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tromino-puzzle-web-dist
        path: tromino-puzzle/dist/web

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Remove current files
        run: rm -rf *

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: tromino-puzzle-web-dist

      - name: Display file structure
        run: |
          ls -R
          git status

      - name: Push GitHub Pages branch commit
        run: |
          git config --global user.name 'Continuous Deployment Job'
          git config --global user.email 'oboukli@users.noreply.github.com'
          git add -A
          git commit -am "Automated deployment"
          git push
