name: Emscripten build for WebAssembly

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      BUILD_PATH: ${{ github.workspace }}/tromino-puzzle/dist/web

    steps:
      - name: Check out Emscripten repository
        uses: actions/checkout@v3
        with:
          repository: emscripten-core/emsdk
          path: emsdk
          persist-credentials: false

      - name: Emscripten SDK cache
        id: emscripten-sdk-cache
        uses: actions/cache@v3
        with:
          path: |-
            emsdk/node
            emsdk/upstream
          key: >-
            emscripten-sdk-cache-${{ hashFiles(
              'emsdk/upstream/emscripten/emscripten-revision.txt'
            ) }}

      - name: Install Emscripten SDK
        env:
          EMSDK_VERSION: 3.1.42
        run: |-
          ./emsdk install "${EMSDK_VERSION}"
          ./emsdk activate "${EMSDK_VERSION}"
        working-directory: emsdk

      - name: Check out main repository
        uses: actions/checkout@v3
        with:
          path: tromino-puzzle
          persist-credentials: false

      - name: Make
        run: |-
          source ${{ github.workspace }}/emsdk/emsdk_env.sh
          emmake make --jobs=$((($(nproc) * 15) / 10))
        working-directory: tromino-puzzle/emscripten

      - name: Archive files
        run: tar --create --file=dist.tar ./*
        working-directory: ${{ env.BUILD_PATH }}

      - name: Archive web app artifacts
        uses: actions/upload-artifact@v3
        continue-on-error: false
        with:
          name: tromino-puzzle-web-dist
          path: ${{ env.BUILD_PATH }}/dist.tar

      - name: Compute SHA256 of artifacts
        run: |-
          ls -Al ./scripts/litro/ | grep -v '^d'
          ls -Al ./scripts/trmn/ | grep -v '^d'
          sha256sum --binary ./dist.tar
          sha256sum --binary ./scripts/litro/litro-wasm.js
          sha256sum --binary ./scripts/litro/litro-wasm.wasm
          sha256sum --binary ./scripts/trmn/trmn-wasm.js
          sha256sum --binary ./scripts/trmn/trmn-wasm.wasm
        working-directory: ${{ env.BUILD_PATH }}

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out GitHub Pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          persist-credentials: false

      - name: Remove current files
        run: rm -rf ./*

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: tromino-puzzle-web-dist

      - name: Compute checksum of downloaded artifact
        run: sha256sum --binary ./dist.tar

      - name: Unarchive files
        run: |-
          tar --extract --file=dist.tar
          rm dist.tar

      - name: Display file structure
        run: ls -R

      - name: Git status
        run: git status

      - name: Publish web app to GitHub Pages
        run: |-
          echo "* -text" > .gitattributes
          if [[ $(git diff --stat) != '' ]]; then
            git config --global user.name 'Continuous Deployment Job'
            git config --global user.email 'oboukli@users.noreply.github.com'
            git add --all -- ":!.gitattributes"
            git commit --amend --all --date=now --message='Automated deployment'
            git push --force
          else
            echo 'No web app changes found. Publish step skipped.'
          fi
