# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Emscripten build for WebAssembly

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      BUILD_PATH: ${{ github.workspace }}/tromino-puzzle/dist/web
      EMSDK_VERSION: 3.1.45

    steps:
      - name: Check out Emscripten repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.EMSDK_VERSION }}
          repository: emscripten-core/emsdk
          path: emsdk
          persist-credentials: false

      - name: Emscripten SDK cache
        id: emscripten-sdk-cache
        uses: actions/cache@v3
        with:
          path: |-
            emsdk/downloads
            emsdk/node
            emsdk/upstream
          key: >-
            emscripten-sdk-cache-${{ hashFiles(
              'emsdk/emsdk_manifest.json'
            ) }}

      - name: Install Emscripten SDK
        run: |-
          ./emsdk install "${EMSDK_VERSION}"
          ./emsdk activate "${EMSDK_VERSION}"
        working-directory: emsdk

      - name: Check out main repository
        uses: actions/checkout@v3
        with:
          path: tromino-puzzle
          persist-credentials: false

      - name: Make
        run: |-
          source ${{ github.workspace }}/emsdk/emsdk_env.sh
          emmake make --jobs=$((($(nproc) * 15) / 10))
        working-directory: tromino-puzzle/emscripten

      - name: Archive build artifacts
        run: tar --create --file=dist.tar ./*
        working-directory: ${{ env.BUILD_PATH }}

      - name: Compute SHA512 of artifacts
        run: |-
          ls -Al ./scripts/litro/ | grep -v '^d'
          ls -Al ./scripts/trmn/ | grep -v '^d'
          sha512sum --binary ./dist.tar
          sha512sum --binary ./scripts/litro/litro-wasm.js
          sha512sum --binary ./scripts/litro/litro-wasm.wasm
          sha512sum --binary ./scripts/trmn/trmn-wasm.js
          sha512sum --binary ./scripts/trmn/trmn-wasm.wasm
        working-directory: ${{ env.BUILD_PATH }}

      - name: Store build artifacts archive
        uses: actions/upload-artifact@v3
        continue-on-error: false
        with:
          name: tromino-puzzle-web-dist
          path: ${{ env.BUILD_PATH }}/dist.tar

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Check out GitHub Pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Remove current files
        run: git rm -r '*'

      - name: Download build artifact archive
        uses: actions/download-artifact@v3
        with:
          name: tromino-puzzle-web-dist

      - name: Compute checksum of downloaded artifact
        run: sha512sum --binary ./dist.tar

      - name: Unarchive files
        run: |-
          tar --extract --file=dist.tar
          rm ./dist.tar

      - name: Display file structure
        run: ls -R

      - name: Publish web app to GitHub Pages
        run: |-
          echo "* -text" > .gitattributes
          if git diff --exit-code ; then
            git config --global user.name 'Continuous Deployment Job'
            git config --global user.email 'oboukli@users.noreply.github.com'
            git add --all -- ":!.gitattributes"
            git status
            git commit --amend --all --date=now --message='Automated deployment'
            git push --force
          else
            echo 'No web app changes found. Publish step skipped.'
          fi
