# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Install markdownlint-cli
        run: sudo npm install --global markdownlint-cli

      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run markdownlint
        run: markdownlint '.'

  superlinter:
    name: Super-Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # HTML_FILE_NAME: ${{ github.workspace }}/.htmlhintrc
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_HTML: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
