# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
  push:
    branches:
      - main
    paths:
      - "**.md"
  workflow_dispatch:

permissions: {}

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Install markdownlint-cli
        run: sudo npm install --global markdownlint-cli

      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run markdownlint
        run: markdownlint .
