# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: GNU Autotools build on Ubuntu

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    env:
      BUILD_PATH: ${{ github.workspace }}/build
      CC: /usr/bin/gcc-14
      CXX: /usr/bin/g++-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update dependency list
        run: sudo apt-get update

      - name: Install dependencies
        run: >-
          sudo apt-get install
          --assume-yes
          --quiet
          autoconf-archive
          g++-14
          gcc-14
          libboost-test-dev
          libsdl2-dev

      - name: Create build directory
        run: mkdir '${{ env.BUILD_PATH }}'

      - name: Run autogen.sh
        run: ./autogen.sh

      - name: Configure build
        run: ../configure
        working-directory: ${{ env.BUILD_PATH }}

      - name: Make
        run: make --jobs=$((($(nproc) * 15) / 10))
        working-directory: ${{ env.BUILD_PATH }}

      - name: Test
        run: make check
        working-directory: ${{ env.BUILD_PATH }}

      - name: Package
        run: make dist
        working-directory: ${{ env.BUILD_PATH }}

      - name: Test package
        run: make distcheck
        working-directory: ${{ env.BUILD_PATH }}

      - name: Install
        run: sudo make install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Run smoke test
        run: tromino 2 0 0

      - name: Compute SHA512 of artifacts
        run: |-
          ls -Al './' | grep -v '^d'
          sha512sum --binary 'libtromino-gfx2d.la'
          sha512sum --binary 'libtromino-validation.la'
          sha512sum --binary 'libtromino.la'
          sha512sum --binary 'libtromino_test'
          sha512sum --binary 'tromino'
          sha512sum --binary 'tromino2d'
          find . -type f -name 'trmnpzzl-*.tar.gz' \
          -exec sha512sum --binary {} \; -quit
        working-directory: ${{ env.BUILD_PATH }}
