name: Build for GNU/Linux

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq autoconf-archive libboost-test-dev libsdl2-dev

    - name: Run autogen.sh
      run: ./autogen.sh

    - name: Configure build
      run: mkdir build && cd build && ../configure

    - name: Make
      run: make -j $((($(nproc) * 15) / 10))
      working-directory: build

    - name: Test
      run: make check
      working-directory: build

    - name: Package
      run: make dist
      working-directory: build

    - name: Test package
      run: make distcheck
      working-directory: build
