# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: GNU Autotools build on Ubuntu

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      BUILD_PATH: ${{ github.workspace }}/build

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update dependency list
        run: sudo apt-get update

      - name: Install dependencies
        run: >-
          sudo apt-get install
          --assume-yes
          --quiet
          autoconf-archive
          libboost-test-dev
          libsdl2-dev

      - name: Run autogen.sh
        run: ./autogen.sh

      - name: Configure build
        run: |-
          mkdir '${{ env.BUILD_PATH }}'
          cd '${{ env.BUILD_PATH }}'
          ../configure

      - name: Make
        run: make --jobs=$((($(nproc) * 15) / 10))
        working-directory: ${{ env.BUILD_PATH }}

      - name: Test
        run: make check
        working-directory: ${{ env.BUILD_PATH }}

      - name: Package
        run: make dist
        working-directory: ${{ env.BUILD_PATH }}

      - name: Test package
        run: make distcheck
        working-directory: ${{ env.BUILD_PATH }}

      - name: Compute SHA512 of artifacts
        run: |-
          ls -Al ./src/ | grep -v '^d'
          ls -Al ./src/.libs/ | grep -v '^d'
          ls -Al ./test/ | grep -v '^d'
          sha512sum --binary ./src/.libs/libtromino.a
          sha512sum --binary ./src/.libs/libtromino-gfx2d.a
          sha512sum --binary ./src/.libs/libtromino-validation.a
          sha512sum --binary ./src/tromino
          sha512sum --binary ./src/tromino2d
          sha512sum --binary ./test/libtromino_test
        working-directory: ${{ env.BUILD_PATH }}
