name: Build on Ubuntu via CMake

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update dependency list
        run: sudo apt-get update

      - name: Install dependencies
        run: >-
          sudo apt-get install
          --assume-yes
          --quiet
          cmake
          libboost-test-dev
          libsdl2-dev

      - name: Configure build with CMake
        run: |-
          mkdir build
          cd build
          cmake ..

      - name: Make
        run: make --jobs=$((($(nproc) * 15) / 10))
        working-directory: build

      - name: Test
        run: make check
        working-directory: build

      - name: Package
        run: make dist
        working-directory: build

      - name: Test package
        run: make distcheck
        working-directory: build
