name: Microsoft C++ Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 43 12 * * 2

env:
  build: ${{ github.workspace }}
  config: Debug

permissions: {}

jobs:
  analyze:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          persist-credentials: false

      - name: Check out vcpkg
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          repository: microsoft/vcpkg
          path: ${{ github.workspace }}\vcpkg
          persist-credentials: false

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      - name: Install Vcpkg packages
        run: |-
          vcpkg install nameof --triplet x64-windows
          vcpkg install nanobench --triplet x64-windows
        working-directory: vcpkg

      - name: Configure CMake
        run: cmake -B ${{ env.build }} -DCMAKE_BUILD_TYPE=${{ env.config }}

      - name: Initialize MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@24c285ab36952c9e9182f4b78dfafbac38a7e5ee
        id: run-analysis
        with:
          buildConfiguration: ${{ env.config }}
          cmakeBuildDirectory: ${{ env.build }}
          ruleset: NativeRecommendedRules.ruleset

      - name: Upload result to GitHub
        uses: github/codeql-action/upload-sarif@8e0b1c74b1d5a0077b04d064c76ee714d3da7637
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}

      - name: Upload result as an artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: sarif-file
          path: ${{ steps.run-analysis.outputs.sarif }}
