# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: OpenSSF Scorecard supply chain security analysis

on:
  branch_protection_rule:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: 33 1 * * 6

permissions: {}

jobs:
  analyze:
    name: Run OpenSSF Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check out repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # tag: v3.6.0
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # tag: v2.2.0
        with:
          results_file: openssf-scorecard.sarif
          results_format: sarif

      - name: Report analysis results to GitHub
        uses: github/codeql-action/upload-sarif@e4262713b504983e61c7728f5452be240d9385a7 # tag: v2.14.3
        with:
          sarif_file: openssf-scorecard.sarif
