name: MSBuild build on Windows

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: msbuild\TrominoPuzzle.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check out vcpkg
        uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          path: ${{ github.workspace }}\vcpkg

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      - name: Apply vcpkg cache
        id: vcpkg-cache
        uses: actions/cache@v3
        with:
          path: |-
            %VCPKG_DEFAULT_BINARY_CACHE%
            ${{ github.workspace }}\vcpkg
          key: >-
            ${{ runner.os }}-vcpkg-archives-cache-${{ hashFiles(
              'vcpkg/ports/boost-test/vcpkg.json',
              'vcpkg/ports/sdl2/vcpkg.json'
            ) }}

      - name: Install Boost.Test vcpkg package
        run: vcpkg install boost-test --triplet x64-windows
        working-directory: vcpkg

      - name: Install SDL2 vcpkg package
        run: vcpkg install sdl2 --triplet x64-windows
        working-directory: vcpkg

      - name: Integrate vcpkg
        run: vcpkg integrate install
        working-directory: vcpkg

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64

      - name: Build
        working-directory: ${{ github.workspace }}
        run: >-
          msbuild
          -detailedSummary
          -maxCpuCount
          -property:Configuration=${{ env.BUILD_CONFIGURATION }}
          -property:Platform=${{ env.BUILD_PLATFORM }}
          -validate
          -warnAsError
          ${{ env.SOLUTION_FILE_PATH }}
