name: MSBuild

on:
  pull_request:
  push:

env:
  SOLUTION_FILE_PATH: msbuild\TrominoPuzzle.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{ github.workspace }}
      run: >
        msbuild
        -detailedSummary
        -maxCpuCount
        -property:Configuration=${{ env.BUILD_CONFIGURATION }}
        -property:Platform=${{ env.BUILD_PLATFORM }}
        -validate
        -warnAsError
        ${{ env.SOLUTION_FILE_PATH }}
